### ISSUE TITLE
训练报错 safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by stella0909** [aigc-apps/sd-webui-EasyPhoto#103]
### 这是否存在现有问题？

我已经搜索了现有问题并检查了最近的构建/提交，但是大家的讨论太少了无法确认我的问题。

### 发生了什么事？

我在进行模型训练的时候，出现错误，但是我并不能够定位到错误出现的原因。
最前面的一个错误是：
{'prediction_type', 'timestep_spacing', 'clip_sample_range', 'dynamic_thresholding_ratio', 'thresholding', 'variance_type', 'sample_max_value'} was not found in config. Values will be initialized to default values.
下一个错误是
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
再下个错误
subprocess.CalledProcessError:

### 重现问题的步骤
1、第一次训练的时候，要求 enable queue，于是我删除了webui-user.bat中的 ---no-gradio-queue。并且在后来的训练中不再魔法上网。

2、根据建议，我也把dataloader num workers调整为0.

3、后来训练的时候，出现大量错误，最近一个相关的错误是safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer...

4、看了B站视频，逐条看了大大和我的运行后台的区别。到这里大大的进度条就是loading各种插件了...我却没有加载，我没有train_kohya的文件夹，只有个train_kohya_log.txt的文件啊

### 系统信息
Python 3.10.6 
pytorch：2.0.1+cu118
windows 11
tensorflow-cpu: 2.13.0
CUDA: 12.2
没有安装CUDNN（这是否有影响？）
GPU: Nvidia Geforce RTX 3060

### 控制台日志

09/20/2023 01:54:03 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

{'prediction_type', 'timestep_spacing', 'dynamic_thresholding_ratio', 'sample_max_value', 'variance_type', 'thresholding', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto-main\scripts\train_kohya\train_lora.py", line 1441, in <module>
    main()
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto-main\scripts\train_kohya\train_lora.py", line 854, in main
    text_encoder, vae, unet = load_models_from_stable_diffusion_checkpoint(False, args.pretrained_model_ckpt)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto-main\scripts\train_kohya\utils\model_utils.py", line 842, in load_models_from_stable_diffusion_checkpoint
    _, state_dict = load_checkpoint_with_text_encoder_conversion(ckpt_path, device)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto-main\scripts\train_kohya\utils\model_utils.py", line 818, in load_checkpoint_with_text_encoder_conversion
    state_dict = load_file(ckpt_path)  # , device) # may causes error
  File "F:\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
Traceback (most recent call last):
  File "C:\Users\张小猫\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\张小猫\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\launch.py", line 989, in <module>
    main()
  File "F:\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\launch.py", line 985, in main
    launch_command(args)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\launch.py", line 979, in launch_command
    simple_launcher(args)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\stable-diffusion-webui\\venv\\Scripts\\python.exe', 'F:\\stable-diffusion-webui\\extensions\\sd-webui-EasyPhoto-main\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto-main\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\taolaoshi\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\taolaoshi\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\taolaoshi\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto-main\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=taolaoshi', '--cache_log_file=F:\\stable-diffusion-webui\\extensions\\sd-webui-EasyPhoto-main\\train_kohya_log.txt', '--validation']' returned non-zero exit status 1.
Error executing the command: Command '['F:\\stable-diffusion-webui\\venv\\Scripts\\python.exe', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', 'F:\\stable-diffusion-webui\\extensions\\sd-webui-EasyPhoto-main\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto-main\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\taolaoshi\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\taolaoshi\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\taolaoshi\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto-main\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=taolaoshi', '--cache_log_file=F:\\stable-diffusion-webui\\extensions\\sd-webui-EasyPhoto-main\\train_kohya_log.txt', '--validation']' returned non-zero exit status 1.

### 其他信息

当我尝试Inference的时候，报错情况：
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
Start Downloading weights
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto-main\scripts\easyphoto_infer.py", line 231, in easyphoto_infer_forward
    best_outputs_paths = glob.glob(os.path.join(user_id_outpath_samples, user_id, "user_weights", "best_outputs", "*.jpg"))
  File "C:\Users\张小猫\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\张小猫\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
Start Downloading weights
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto-main\scripts\easyphoto_infer.py", line 231, in easyphoto_infer_forward
    best_outputs_paths = glob.glob(os.path.join(user_id_outpath_samples, user_id, "user_weights", "best_outputs", "*.jpg"))
  File "C:\Users\张小猫\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\张小猫\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

毕竟不是程序猿，完全看不懂为啥错啊。。。

**Comment by yunkchen** [comment]
确认下ChilloutMix模型是否下载成功了（models/Stable-diffusion下）
