### ISSUE TITLE
[网络问题导致modelscope模型无法加载] Can not generate photos after training

### ISSUE THREAD

**Issue by Geekgulu** [aigc-apps/sd-webui-EasyPhoto#128]
After training, I switched to the inference page. but when I started generation, an error appeared in the result. Below is the log shown in the terminal. Could you help to analyse what is the problem and how to resolve it? Thanks.

Start Downloading weights
2023-09-26 10:19:51,897 - modelscope - INFO - Use user-specified model revision: v1.3
Traceback (most recent call last):
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\modelscope\hub\file_download.py", line 309, in http_get_file
    r.raise_for_status()
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://www.modelscope.cn/api/v1/models/damo/cv_unet-image-face-fusion_damo/repo?Revision=v1.3&FilePath=description/.DS_Store

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sd\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 196, in easyphoto_infer_forward
    image_face_fusion       = pipeline(Tasks.image_face_fusion, model='damo/cv_unet-image-face-fusion_damo', model_revision='v1.3')
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\builder.py", line 115, in pipeline
    model = normalize_model_input(
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\modelscope\pipelines\builder.py", line 36, in normalize_model_input
    model = snapshot_download(
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\modelscope\hub\snapshot_download.py", line 149, in snapshot_download
    http_get_file(
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\modelscope\hub\file_download.py", line 329, in http_get_file
    retry = retry.increment('GET', url, error=e)
  File "D:\sd\stable-diffusion-webui\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: None: Max retries exceeded with url: http://www.modelscope.cn/api/v1/models/damo/cv_unet-image-face-fusion_damo/repo?Revision=v1.3&FilePath=description/.DS_Store (Caused by HTTPError('502 Server Error: Bad Gateway for url: http://www.modelscope.cn/api/v1/models/damo/cv_unet-image-face-fusion_damo/repo?Revision=v1.3&FilePath=description/.DS_Store'))

**Comment by wuziheng** [comment]
常见问题，参考WIKI， 网络环境导致获取modelscope 模型失败，多尝试几次即可。
