### ISSUE TITLE
家里网络出问题了，断网了。然后使用这个插件进行推理时，提示错误，提示链接服务器失败

### ISSUE THREAD

**Issue by wibur0620** [aigc-apps/sd-webui-EasyPhoto#143]
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000014D7BE981C0>, 'Connection to pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com', port=443): Max retries exceeded with url: /webui/ChilloutMix-ni-fp16.safetensors (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000014D7BE981C0>, 'Connection to pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 210, in easyphoto_infer_forward
    check_files_exists_and_download(check_hash)
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_utils.py", line 97, in check_files_exists_and_download
    if os.path.exists(filename) and compare_hasd_link_file(url, filename):
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_utils.py", line 105, in compare_hasd_link_file
    r           = requests.head(url)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com', port=443): Max retries exceeded with url: /webui/ChilloutMix-ni-fp16.safetensors (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000014D7BE981C0>, 'Connection to pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com timed out. (connect timeout=None)'))

**Comment by wibur0620** [comment]
当链接网络后也有能正常使用了

**Comment by wuziheng** [comment]
收到。
