### ISSUE TITLE
    RuntimeError: model not found: None

### ISSUE THREAD

**Issue by cnwellin** [aigc-apps/sd-webui-EasyPhoto#150]
我能正常训练、生成图片，但推理过程总有一段错误信息，缺少什么吗？
*** Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 495, in process
        script_args = p.script_args[script.args_from:script.args_to]
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 339, in build_control_model
        raise RuntimeError(f"model not found: {model}")
    RuntimeError: model not found: None

**Comment by wuziheng** [comment]
能提供一下你的使用的环境么，似乎是WebUI版本过低，起码要1.4，如果是秋叶整合包最好是4.4

**Comment by cnwellin** [comment]
python 3.10.6  WebUI 1.5 RC

**Comment by cnwellin** [comment]
感觉像是我的controlNet缺少东西，这段报错信息过后，就是正常进度条了

**Comment by Xelawk** [comment]
> 感觉像是我的controlNet缺少东西，这段报错信息过后，就是正常进度条了

结果正确吗，会不会影响最终效果

**Comment by wuziheng** [comment]
如果最后出图没有问题，麻烦提醒一下关闭issue，我们会在24h内关闭这个issue

**Comment by BuQingYan** [comment]
问题解决了吗，我这里出现的相同的报错，controlnet单独使用是正常的

**Comment by wuziheng** [comment]
升级webui版本可以解决。
