### ISSUE TITLE
[venv]ModuleNotFoundError: No module named 'venv'

### ISSUE THREAD

**Issue by xiaops2005** [aigc-apps/sd-webui-EasyPhoto#157]
启动SD时报下面的错，不知道啥原因，用的秋叶的整合包。
*** Error loading script: preprocess.py
    Traceback (most recent call last):
      File "G:\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\preprocess.py", line 16, in <module>
        from modelscope.pipelines import pipeline
      File "G:\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "G:\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\base.py", line 15, in <module>
        from modelscope.models.base import Model
      File "G:\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\__init__.py", line 8, in <module>
        from .base import Head, Model
      File "G:\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\__init__.py", line 4, in <module>
        from .base_head import *  # noqa F403
      File "G:\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_head.py", line 5, in <module>
        from modelscope.models.base.base_model import Model
      File "G:\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_model.py", line 15, in <module>
        from modelscope.utils.plugins import (register_modelhub_repo,
      File "G:\sd-webui-aki-v4\py310\lib\site-packages\modelscope\utils\plugins.py", line 12, in <module>
        import venv
    ModuleNotFoundError: No module named 'venv'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by wuziheng** [comment]
在秋叶的后台手动安装venv 环境试试？

**Comment by xiaops2005** [comment]
> 在秋叶的后台手动安装venv 环境试试？

哪个后台安装啊？怎么安装我也不清楚

**Comment by wuziheng** [comment]
一般来说，重启一次可以解决这一问题。请试试，使用群公告提示的4.4版本。

**Comment by bubbliiiing** [comment]
> > 一般来说，重启一次可以解决这一问题。请试试，使用群公告提示的4.4版本。
> 
> 启动器用的最新的2.5.0，SD也是最新的1.6.0，每次启动都报这个错。

hihi，启动器的下载地址可以给一下吗？

**Comment by wenmengzhou** [comment]
modelscope master已修复从modelscope master安装，1.9.3版本下周发布会包含这个修复

**Comment by orzlenmo** [comment]
你可以先去你得系统python环境里目录里面把venv这个库文件夹整个复制到你秋叶环境下python 环境插件目录里，比我的电脑我是把C:\Program Files\python310\Lib中的venv文件夹 复制到D:\AiImage\novelai-webui-aki-v3\py310\Lib\site-packages下

**Comment by wuziheng** [comment]
@wenmengzhou @orzlenmo @jiehwa @xiaops2005  @bubbliiiing 
似乎可以合并到venv 问题 https://github.com/modelscope/modelscope/issues/572

**Comment by xiaops2005** [comment]
更新EasyPhoto插件以后就不报错了
