### ISSUE TITLE
 [模板图片需要能够检测出人脸]无法生成预测图像

### ISSUE THREAD

**Issue by jjboy0524** [aigc-apps/sd-webui-EasyPhoto#168]
选中user id后进行图片生成，遇到如下报错
Traceback (most recent call last):
  File "E:\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 316, in easyphoto_infer_forward
    _face_id_retinaface_box      = _face_id_retinaface_boxes[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by wuziheng** [comment]
这个是由于模板图片没有检测到合适的人脸导致的。请提供出错的模板图片
