### ISSUE TITLE
webUI上没有显示Easyphoto插件

### ISSUE THREAD

**Issue by giuliano1101** [aigc-apps/sd-webui-EasyPhoto#181]
安装插件后，在webui中没有出现easyphoto的插件。从webui中下载，gitclone，已经从github上下载zip文件后解压到文件夹中都尝试过了，依然失败。在扩展的已安装中能够看到已经安装了easyphoto。我用的是秋叶大佬的启动器，尝试了几个不同的核心版本，依然没出现插件。不知哪位大佬直到如何解决这个问题？
![1697532461358](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/128056835/ef1f06db-afe9-4cbd-9e81-62e1078d0428)

**Comment by yunkchen** [comment]
可以贴一下日志，应该是依赖的环境或者模型没有安装/下载成功

**Comment by haiyongsong1921** [comment]
web-ui的插件安装后，要重启web-ui

**Comment by gttown2023** [comment]
同样的问题，下载安装重启后并没有出现插件，但是显示已安装，po主问题解决了吗

**Comment by Matata618** [comment]
我的娃也是，不显示而且有他有提示i错误
Error loading script: preprocess.py
    Traceback (most recent call last):
      File "D:\software\novelai-webui-aki-v3\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\software\novelai-webui-aki-v3\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\software\novelai-webui-aki-v3\extensions\sd-webui-EasyPhoto\scripts\preprocess.py", line 16, in <module>
        from modelscope.outputs import OutputKeys
    ModuleNotFoundError: No module named 'modelscope'

**Comment by jiangxinufo** [comment]
同样的问题，下载安装重启后并没有出现插件，但是显示已安装，po主问题解决了吗

**Comment by werran2** [comment]
同样的问题
*** Error loading script: easyphoto_infer.py
    Traceback (most recent call last):
      File "F:\novelai-webui-aki-v3\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\novelai-webui-aki-v3\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\novelai-webui-aki-v3\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 11, in <module>
        from modelscope.outputs import OutputKeys
    ModuleNotFoundError: No module named 'modelscope'

---
*** Error loading script: easyphoto_train.py
    Traceback (most recent call last):
      File "F:\novelai-webui-aki-v3\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\novelai-webui-aki-v3\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\novelai-webui-aki-v3\extensions\sd-webui-EasyPhoto\scripts\easyphoto_train.py", line 21, in <module>
        from scripts.easyphoto_utils import check_files_exists_and_download, check_id_valid, check_scene_valid, unload_models
      File "F:\novelai-webui-aki-v3\extensions\sd-webui-EasyPhoto\scripts\easyphoto_utils\__init__.py", line 12, in <module>
        from .tryon_utils import (
      File "F:\novelai-webui-aki-v3\extensions\sd-webui-EasyPhoto\scripts\easyphoto_utils\tryon_utils.py", line 13, in <module>
        from shapely.geometry import Polygon
    ModuleNotFoundError: No module named 'shapely'

---
*** Error loading script: easyphoto_tryon_infer.py
    Traceback (most recent call last):
      File "F:\novelai-webui-aki-v3\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\novelai-webui-aki-v3\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\novelai-webui-aki-v3\extensions\sd-webui-EasyPhoto\scripts\easyphoto_tryon_infer.py", line 16, in <module>
        from segment_anything import SamPredictor, sam_model_registry
    ModuleNotFoundError: No module named 'segment_anything'

---
*** Error loading script: easyphoto_ui.py
    Traceback (most recent call last):
      File "F:\novelai-webui-aki-v3\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\novelai-webui-aki-v3\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\novelai-webui-aki-v3\extensions\sd-webui-EasyPhoto\scripts\easyphoto_ui.py", line 22, in <module>
        from scripts.easyphoto_infer import easyphoto_infer_forward, easyphoto_video_infer_forward
      File "F:\novelai-webui-aki-v3\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 11, in <module>
        from modelscope.outputs import OutputKeys
    ModuleNotFoundError: No module named 'modelscope'

**Comment by Xiehan123** [comment]
你可以在启动软件中的：版本管理--内核   切换到一个比较新的内核，然后重新安装插件试一下，亲测有效，猜测是因为版本比较旧缺乏插件所需的依赖库

**Comment by Bingo-QX** [comment]
> 你可以在启动软件中的：版本管理--内核 切换到一个比较新的内核，然后重新安装插件试一下，亲测有效，猜测是因为版本比较旧缺乏插件所需的依赖库你可以在启动软件中的：版本管理--内核 切换到一个比较新的内核，然后重新安装插件试一下，亲测有效，猜测是因为版本比较旧缺乏插件所需的依赖库你可以在启动软件中的：版本管理--内核 切换到一个比较新的内核，然后重新安装插件试一下，亲测有效，猜测是因为版本比较旧缺乏插件所需的依赖库

请问这个要怎么操作呢？

**Comment by zouxinyi0625** [comment]
> > 你可以在启动软件中的：版本管理--内核 切换到一个比较新的内核，然后重新安装插件试一下，亲测有效，猜测是因为版本比较旧缺乏插件所需的依赖库你可以在启动软件中的：版本管理--内核 切换到一个比较新的内核，然后重新安装插件试一下，亲测有效，猜测是因为版本比较旧缺乏插件所需的依赖库你可以在启动软件中的：版本管理--内核 切换到一个比较新的内核，然后重新安装插件试一下，亲测有效，猜测是因为版本比较旧缺乏插件所需的依赖库
> 
> 请问这个要怎么操作呢？

加一下主页的群，在群里贴具体报错的log吧，会有同学帮忙解决的。

**Comment by lele1122** [comment]
同样的问题，这些包都安装了还是显示找不到

**Comment by danillip** [comment]
_**Для русского комюнити:**_
**Открываете папку** Data\Packages\stable-diffusion-webui\venv\Scripts
И в строке пути прописываете эти две команды. По очереди!
```
pip install huggingface_hub==0.13.4
pip install --upgrade diffusers huggingface_hub
```
Перезапускаете Stable и все должно работать, начнется закачка файлов и вкладка EasyPhoto появится. 

**_For eng comunity:_**
**Open the** Data\Packages\stable-diffusion-webui\venv\Scripts folder.
And in the path line write these two commands.  One at a time!
```
pip install huggingface_hub==0.13.4
pip install --upgrade diffusers huggingface_hub
```
Restart Stable and everything should work, files will start downloading and EasyPhoto tab will appear.

**Comment by lihuikenny** [comment]
> web-ui的插件安装后，要重启web-ui

请教一下，如何启动web-ui,哪个脚本？
