### ISSUE TITLE
api请求：两个请求先后发出报错。Template 1 error: Error info is 'NoneType' object has no attribute 'ema_scope'.

### ISSUE THREAD

**Issue by yangdeai** [aigc-apps/sd-webui-EasyPhoto#182]
使用同一套api请求代码，先后请求时报错。一个成功一个报错。单独一个请求时正常。
客户端：
outputs: {'message': "Template 1 error: Error info is 'NoneType' object has no attribute 'ema_scope'.", 'outputs': [], 'face_id_outputs': []}

服务器后台：
2023-10-17 07:28:43,694 - ControlNet - INFO - controlnet_default_config
*** Error running process: /test/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/test/stable-diffusion-webui/modules/scripts.py", line 658, in process
        script.process(p, *script_args)
      File "/test/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "/test/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/test/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "/test/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "/test/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 350, in build_control_model
        network = build_model_by_guess(state_dict, unet, model_path)
      File "/test/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_model_guess.py", line 185, in build_model_by_guess
        network = PlugableControlModel(config, state_dict)
      File "/test/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 21, in __init__
        self.control_model = ControlNet(**self.config).cpu()
      File "/opt/conda/envs/roop/lib/python3.10/site-packages/torch/nn/modules/module.py", line 954, in cpu
        return self._apply(lambda t: t.cpu())
      File "/opt/conda/envs/roop/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
        module._apply(fn)
      File "/opt/conda/envs/roop/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
        module._apply(fn)
      File "/opt/conda/envs/roop/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
        param_applied = fn(param)
      File "/opt/conda/envs/roop/lib/python3.10/site-packages/torch/nn/modules/module.py", line 954, in <lambda>
        return self._apply(lambda t: t.cpu())
    NotImplementedError: Cannot copy out of meta tensor; no data!

post_infer1.py 和post_infer2.py 是用一套代码。代码如下：

`
import base64
import json
import sys
import time
from datetime import datetime
from io import BytesIO

import cv2
import numpy as np
import requests

def decode_image_from_base64jpeg(base64_image):
    image_bytes = base64.b64decode(base64_image)
    np_arr = np.frombuffer(image_bytes, np.uint8)
    image = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
    return image

def post(encoded_image, url='http://192.168.1.215:8001'): 
    datas = json.dumps({
        "user_ids"              : ["jst"],
        "sd_model_checkpoint"   : "Chilloutmix-Ni-pruned-fp16-fix.safetensors",
        "init_image"            : encoded_image,

        "first_diffusion_steps"     : 50,
        "first_denoising_strength"  : 0.45,
        "second_diffusion_steps"    : 20,
        "second_denoising_strength" : 0.35,
        "seed"                      : 12345, 
        "crop_face_preprocess"      : True,

        "before_face_fusion_ratio"  : 0.5,
        "after_face_fusion_ratio"   : 0.5,
        "apply_face_fusion_before"  : True,
        "apply_face_fusion_after"   : True,

        "color_shift_middle"        : True,
        "color_shift_last"          : True,
        "super_resolution"          : True,
        "background_restore"        : False,
        "tabs"                      : 1  # 1
    })
    r = requests.post(f'{url}/easyphoto/easyphoto_infer_forward', data=datas, timeout=50000)
    data = r.content.decode('utf-8')
    return data

if __name__ == '__main__':
    '''
    There are two ways to test:
        The first: make sure the directory is full of readable images
        The second: public link of readable picture
    '''

    now_date    = datetime.now()
    time_start  = time.time()  
    
    images_list = ['white2.png']
    for image_file in images_list:
            with open(image_file, 'rb') as f:
                encoded_image = base64.b64encode(f.read()).decode('utf-8')
                outputs = post(encoded_image)
                outputs = json.loads(outputs)
                print(f"outputs: {outputs['message']}")
                print(f"outputs: {outputs['face_id_outputs']}")
                image = decode_image_from_base64jpeg(outputs["outputs"][0])
                cv2.imwrite(f"{now_date.hour}-{now_date.minute}-{now_date.second}" + ".jpg", image)

    time_end = time.time()  
    time_sum = (time_end - time_start) % 60 
    print('# --------------------------------------------------------- #')
    print(f'#   Total expenditure: {time_sum}s')
    print('# --------------------------------------------------------- #')

`

**Comment by wuziheng** [comment]
当前线上版本其实对并发的支持可能是有问题的，如果需要并发使用可能需要自行实现排队，或者咨询Wiki中提到的SAAS服务，可以支持排队，并发等功能。
如果单独调用API 没有问题，我们会关闭此ISSUE
