### ISSUE TITLE
No module named 'modelscope.t2v_model'

### ISSUE THREAD

**Issue by BuQingYan** [aigc-apps/sd-webui-EasyPhoto#183]
秋叶SD控制台启动日志：
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Fetching updates for Stable Diffusion...
Checking out commit for Stable Diffusion with hash: cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf...
Active code page: 65001
HEAD is now at cf1d67a Update modelcard.md
Fetching updates for Stable Diffusion XL...
Checking out commit for Stable Diffusion XL with hash: 45c443b316737a4ab6e40413d7794a7f5657c19f...
Active code page: 65001
HEAD is now at 45c443b Fix license-files setting for project (#71)
Fetching updates for K-diffusion...
Checking out commit for K-diffusion with hash: ab527a9a6d347f364e3d185ba6d714e22d80cb3c...
Active code page: 65001
HEAD is now at ab527a9 Release 0.0.16
Fetching updates for CodeFormer...
Checking out commit for CodeFormer with hash: c5b4593074ba6214284d6acd5f1719b6c5d739af...
Active code page: 65001
HEAD is now at c5b4593 add replicate demo.
Fetching updates for BLIP...
Checking out commit for BLIP with hash: 48211a1594f1321b00f14c9f7a5b4813144b2fb9...
Active code page: 65001
HEAD is now at 48211a1 Update README.md
Active code page: 65001
Active code page: 65001
current transparent-background 1.2.3
Active code page: 65001
Active code page: 65001
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
Installing requirements for Face Editor
Active code page: 65001
Active code page: 65001
Active code page: 65001
Installing requirements for easyphoto-webui
Installing requirements for tensorflow
Installing requirements for easyphoto-webui
Installing requirements for modelscope
Installing requirements for easyphoto-webui
Installing requirements for diffusers
Active code page: 65001
Active code page: 65001
Active code page: 65001
Active code page: 65001
Active code page: 65001
Active code page: 65001
Installing requirements for Shift Attention
Active code page: 65001
Active code page: 65001
Active code page: 65001
Launching Web UI with arguments: --port 7872 --opt-sdp-attention --no-half-vae --opt-channelslast --api --listen --enable-insecure-extension-access --allow-code --no-hashing --no-gradio-queue
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
AUTOMATIC1111/stable-diffusion-webui packed by bilibili@秋葉aaaki 
本整合包完全免费，严禁倒卖。若您付费获得本软件请立刻举报商家。
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully

========================= a1111-sd-webui-lycoris =========================
Starting from stable-diffusion-webui version 1.5.0
a1111-sd-webui-lycoris extension is no longer needed

All its features have been integrated into the native LoRA extension
LyCORIS models can now be used as if there are regular LoRA models

This extension has been automatically deactivated
Please remove this extension
==========================================================================

Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.10.0, num models: 11
2023-10-17 18:49:23,812 - modelscope - INFO - PyTorch version 2.0.0+cu118 Found.
2023-10-17 18:49:23,816 - modelscope - INFO - TensorFlow version 2.14.0 Found.
2023-10-17 18:49:23,816 - modelscope - INFO - Loading ast index from E:\wyfx\StableDiffusionService\sd-webui-aki-v4\.cache\modelscope\hub\ast_indexer
2023-10-17 18:49:23,909 - modelscope - INFO - Loading done! Current index file version is 1.8.4, with md5 586fa096c665b11860e22f847a2ce502 and a total number of 902 components indexed
*** Error loading script: api.py
    Traceback (most recent call last):
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\api.py", line 5, in <module>
        from scripts.easyphoto_infer import *
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 10, in <module>
        from modelscope.pipelines import pipeline
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\base.py", line 15, in <module>
        from modelscope.models.base import Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\__init__.py", line 8, in <module>
        from .base import Head, Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\__init__.py", line 4, in <module>
        from .base_head import *  # noqa F403
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_head.py", line 5, in <module>
        from modelscope.models.base.base_model import Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_model.py", line 15, in <module>
        from modelscope.utils.plugins import (register_modelhub_repo,
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\utils\plugins.py", line 12, in <module>
        import venv
    ModuleNotFoundError: No module named 'venv'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: easyphoto_infer.py
    Traceback (most recent call last):
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 10, in <module>
        from modelscope.pipelines import pipeline
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\base.py", line 15, in <module>
        from modelscope.models.base import Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\__init__.py", line 8, in <module>
        from .base import Head, Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\__init__.py", line 4, in <module>
        from .base_head import *  # noqa F403
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_head.py", line 5, in <module>
        from modelscope.models.base.base_model import Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_model.py", line 15, in <module>
        from modelscope.utils.plugins import (register_modelhub_repo,
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\utils\plugins.py", line 12, in <module>
        import venv
    ModuleNotFoundError: No module named 'venv'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: easyphoto_ui.py
    Traceback (most recent call last):
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_ui.py", line 11, in <module>
        from scripts.easyphoto_infer import easyphoto_infer_forward
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 10, in <module>
        from modelscope.pipelines import pipeline
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\base.py", line 15, in <module>
        from modelscope.models.base import Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\__init__.py", line 8, in <module>
        from .base import Head, Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\__init__.py", line 4, in <module>
        from .base_head import *  # noqa F403
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_head.py", line 5, in <module>
        from modelscope.models.base.base_model import Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_model.py", line 15, in <module>
        from modelscope.utils.plugins import (register_modelhub_repo,
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\utils\plugins.py", line 12, in <module>
        import venv
    ModuleNotFoundError: No module named 'venv'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: preprocess.py
    Traceback (most recent call last):
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\preprocess.py", line 16, in <module>
        from modelscope.pipelines import pipeline
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\base.py", line 15, in <module>
        from modelscope.models.base import Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\__init__.py", line 8, in <module>
        from .base import Head, Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\__init__.py", line 4, in <module>
        from .base_head import *  # noqa F403
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_head.py", line 5, in <module>
        from modelscope.models.base.base_model import Model
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_model.py", line 15, in <module>
        from modelscope.utils.plugins import (register_modelhub_repo,
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\py310\lib\site-packages\modelscope\utils\plugins.py", line 12, in <module>
        import venv
    ModuleNotFoundError: No module named 'venv'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
[AddNet] Updating model hashes...
[AddNet] Updating model hashes...
2023-10-17 18:49:24,794 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: E:\wyfx\StableDiffusionService\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\downloads
2023-10-17 18:49:24,996 - ControlNet - INFO - ControlNet v1.1.410
*** Error loading script: api_t2v.py
    Traceback (most recent call last):
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\extensions\sd-webui-text2video\scripts\api_t2v.py", line 39, in <module>
        from t2v_helpers.args import T2VArgs_sanity_check, T2VArgs, T2VOutputArgs
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4/extensions/sd-webui-text2video/scripts\t2v_helpers\args.py", line 7, in <module>
        from samplers.samplers_common import available_samplers
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4/extensions/sd-webui-text2video/scripts\samplers\samplers_common.py", line 3, in <module>
        from samplers.ddim.gaussian_sampler import GaussianDiffusion
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4/extensions/sd-webui-text2video/scripts\samplers\ddim\gaussian_sampler.py", line 2, in <module>
        from modelscope.t2v_model import _i
    ModuleNotFoundError: No module named 'modelscope.t2v_model'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: text2vid.py
    Traceback (most recent call last):
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4\extensions\sd-webui-text2video\scripts\text2vid.py", line 24, in <module>
        from t2v_helpers.render import run
      File "E:\wyfx\StableDiffusionService\sd-webui-aki-v4/extensions/sd-webui-text2video/scripts\t2v_helpers\render.py", line 5, in <module>
        from modelscope.process_modelscope import process_modelscope
    ModuleNotFoundError: No module named 'modelscope.process_modelscope'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
Loading weights [ea0e2d9257] from E:\wyfx\StableDiffusionService\sd-webui-aki-v4\models\Stable-diffusion\AWPortrait_v1.2.safetensors
Creating model from config: E:\wyfx\StableDiffusionService\sd-webui-aki-v4\configs\v1-inference.yaml
Loading VAE weights specified in settings: E:\wyfx\StableDiffusionService\sd-webui-aki-v4\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: sdp... done.
Model loaded in 4.7s (load weights from disk: 0.2s, create model: 1.0s, apply weights to model: 3.1s, load VAE: 0.2s, calculate empty prompt: 0.1s).
Running on local URL:  http://0.0.0.0:7872

**Comment by chenhui5416** [comment]
+1 请问解决了吗

**Comment by 112292454** [comment]
> ```python
> 2023-11-27 17:14:13,168 - modelscope - INFO - PyTorch version 2.1.0 Found.
> 2023-11-27 17:14:13,170 - modelscope - INFO - Loading ast index from /home/gzy/.cache/modelscope/ast_indexer
> 2023-11-27 17:14:13,193 - modelscope - INFO - Loading done! Current index file version is 1.9.5, with md5 dc2db941758e6cf7545bfc6e8f46abaf and     a total number of 945 components indexed
> *** Error loading script: api_t2v.py
>     Traceback (most recent call last):
>       File "/home/gzy/py/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
>         script_module = script_loading.load_module(scriptfile.path)
>       File "/home/gzy/py/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
>         module_spec.loader.exec_module(module)
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "/home/gzy/py/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/api_t2v.py", line 39, in <module>
>         from t2v_helpers.args import T2VArgs_sanity_check, T2VArgs, T2VOutputArgs
>       File "/home/gzy/py/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/t2v_helpers/args.py", line 7, in <module>
>         from samplers.samplers_common import available_samplers
>       File "/home/gzy/py/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/samplers/samplers_common.py", line 3, in <module>
>         from samplers.ddim.gaussian_sampler import GaussianDiffusion
>       File "/home/gzy/py/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/samplers/ddim/gaussian_sampler.py", line 2, in <module>
>         from modelscope.t2v_model import _i
>     ModuleNotFoundError: No module named 'modelscope.t2v_model'
> 
> ---
> *** Error loading script: text2vid.py
>     Traceback (most recent call last):
>       File "/home/gzy/py/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
>         script_module = script_loading.load_module(scriptfile.path)
>       File "/home/gzy/py/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
>         module_spec.loader.exec_module(module)
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "/home/gzy/py/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/text2vid.py", line 24, in <module>
>         from t2v_helpers.render import run
>       File "/home/gzy/py/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/t2v_helpers/render.py", line 5, in <module>
>         from modelscope.process_modelscope import process_modelscope
>     ModuleNotFoundError: No module named 'modelscope.process_modelscope'
> 
> ---
> ```

草 好像我报错我插件不是这个仓库哈（）
不过都是缺这个东西，上面的解决了我这个应该也可以

**Comment by chozzz** [comment]
+1 not sure what above people said, but I agree.
