### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm.auto' 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

### ISSUE THREAD

**Issue by Vampire-DIO** [aigc-apps/sd-webui-EasyPhoto#187]
发现只要安装额外的插件之后重启就会报这个错误，无法启动运行。
完整报错信息：
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
current transparent-background 1.2.7
Launching Web UI with arguments: --theme dark --xformers --api --autolaunch
Traceback (most recent call last):
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\launch.py", line 48, in <module>
    main()
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\launch.py", line 44, in main
    start()
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\modules\launch_utils.py", line 432, in start
    import webui
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\webui.py", line 13, in <module>
    initialize.imports()
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\modules\initialize.py", line 16, in imports
    import pytorch_lightning  # noqa: F401
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
    from torchmetrics import Metric
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\torchmetrics\functional\__init__.py", line 82, in <module>
    from torchmetrics.functional.text.bleu import bleu_score
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\torchmetrics\functional\text\__init__.py", line 30, in <module>
    from torchmetrics.functional.text.bert import bert_score  # noqa: F401
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\torchmetrics\functional\text\bert.py", line 24, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\torchmetrics\functional\text\helper_embedding_metric.py", line 26, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\transformers\utils\__init__.py", line 30, in <module>
    from .generic import (
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\transformers\utils\generic.py", line 29, in <module>
    from .import_utils import is_flax_available, is_tf_available, is_torch_available, is_torch_fx_proxy
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\transformers\utils\import_utils.py", line 33, in <module>
    from . import logging
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\transformers\utils\logging.py", line 35, in <module>
    import huggingface_hub.utils as hf_hub_utils
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\huggingface_hub\utils\__init__.py", line 18, in <module>
    from . import tqdm as _tqdm  # _tqdm is the module
  File "D:\project\sd\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\huggingface_hub\utils\tqdm.py", line 63, in <module>
    from tqdm.auto import tqdm as old_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

求大佬们帮忙看看怎么个事儿

**Comment by wuziheng** [comment]
似乎不是由我们的依赖引起的问题，可以在秋叶的项目咨询一下
