### ISSUE TITLE
Debug error, warnings etc [RTX 3080] 10gb, nvidia 531.68 drivers

### ISSUE THREAD

**Issue by belenkoksas** [aigc-apps/sd-webui-EasyPhoto#194]
2023-10-20 16:59:29,620 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-10-20 16:59:29,622 - modelscope - INFO - TensorFlow version 2.13.0 Found.
2023-10-20 16:59:29,622 - modelscope - INFO - Loading ast index from  .cache\modelscope\ast_indexer
2023-10-20 16:59:29,656 - modelscope - INFO - Loading done! Current index file version is 1.8.4, with md5 b320989f334a8b84ddb329fefdff397c and a total number of 902 components indexed
2023-10-20 16:59:35,336 - modelscope - INFO - Use user-specified model revision: v1.0.3
2023-10-20 16:59:35,780 - modelscope - WARNING - ('PIPELINES', 'face_recognition', 'face_recognition') not found in ast index file
2023-10-20 16:59:35,780 - modelscope - INFO - initiate model from  .cache\modelscope\hub\bubbliiiing\cv_retinafce_recognition
2023-10-20 16:59:35,780 - modelscope - INFO - initiate model from location  .cache\modelscope\hub\bubbliiiing\cv_retinafce_recognition.
2023-10-20 16:59:35,781 - modelscope - INFO - initialize model from  .cache\modelscope\hub\bubbliiiing\cv_retinafce_recognition
2023-10-20 16:59:35,783 - modelscope - WARNING - ('MODELS', 'face_recognition', 'face_recognition') not found in ast index file
2023-10-20 16:59:37,130 - modelscope - INFO - Model revision not specified, use the latest revision: v2.0.2
2023-10-20 16:59:39,046 - modelscope - INFO - initiate model from  .cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface
2023-10-20 16:59:39,046 - modelscope - INFO - initiate model from location  .cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface.
2023-10-20 16:59:39,049 - modelscope - WARNING - No preprocessor field found in cfg.
2023-10-20 16:59:39,049 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-10-20 16:59:39,049 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': ' \.cache\\modelscope\\hub\\damo\\cv_resnet50_face-detection_retinaface'}. trying to build by task and model information.
2023-10-20 16:59:39,049 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-10-20 16:59:39,050 - modelscope - INFO - loading model from  .cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface\pytorch_model.pt
D:\AI\a1111\venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\AI\a1111\venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
2023-10-20 16:59:39,377 - modelscope - INFO - load model done
2023-10-20 16:59:39,988 - modelscope - INFO - load facefusion models done
2023-10-20 16:59:39,989 - modelscope - INFO - init done
2023-10-20 16:59:39,990 - modelscope - WARNING - No preprocessor field found in cfg.
2023-10-20 16:59:39,990 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-10-20 16:59:39,991 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': ' \.cache\\modelscope\\hub\\bubbliiiing\\cv_retinafce_recognition'}. trying to build by task and model information.
2023-10-20 16:59:39,991 - modelscope - WARNING - No preprocessor key ('face_recognition', 'face_recognition') found in PREPROCESSOR_MAP, skip building preprocessor.
2023-10-20 16:59:39,991 - modelscope - INFO - image face recognition model init done
2023-10-20 16:59:44,475 - modelscope - INFO - Use user-specified model revision: v2.0.2
2023-10-20 16:59:46,699 - modelscope - INFO - initiate model from  .cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface
2023-10-20 16:59:46,699 - modelscope - INFO - initiate model from location  .cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface.
2023-10-20 16:59:46,701 - modelscope - WARNING - No preprocessor field found in cfg.
2023-10-20 16:59:46,702 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-10-20 16:59:46,702 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': ' \.cache\\modelscope\\hub\\damo\\cv_resnet50_face-detection_retinaface'}. trying to build by task and model information.
2023-10-20 16:59:46,702 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-10-20 16:59:46,703 - modelscope - INFO - loading model from  .cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface\pytorch_model.pt
2023-10-20 16:59:46,971 - modelscope - INFO - load model done
2023-10-20 16:59:49,884 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-10-20 16:59:50,327 - modelscope - INFO - initiate model from  .cache\modelscope\hub\damo\cv_u2net_salient-detection
2023-10-20 16:59:50,327 - modelscope - INFO - initiate model from location  .cache\modelscope\hub\damo\cv_u2net_salient-detection.
2023-10-20 16:59:50,328 - modelscope - INFO - initialize model from  .cache\modelscope\hub\damo\cv_u2net_salient-detection
2023-10-20 16:59:50,539 - modelscope - WARNING - No preprocessor field found in cfg.
2023-10-20 16:59:50,540 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-10-20 16:59:50,540 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': ' \.cache\\modelscope\\hub\\damo\\cv_u2net_salient-detection'}. trying to build by task and model information.
2023-10-20 16:59:50,540 - modelscope - WARNING - No preprocessor key ('detection', 'semantic-segmentation') found in PREPROCESSOR_MAP, skip building preprocessor.
2023-10-20 16:59:52,036 - modelscope - INFO - Use user-specified model revision: v1.0.2
2023-10-20 16:59:52,568 - modelscope - WARNING - ('PIPELINES', 'skin-retouching-torch', 'skin-retouching-torch') not found in ast index file
2023-10-20 16:59:52,568 - modelscope - INFO - initiate model from  .cache\modelscope\hub\damo\cv_unet_skin_retouching_torch
2023-10-20 16:59:52,568 - modelscope - INFO - initiate model from location  .cache\modelscope\hub\damo\cv_unet_skin_retouching_torch.
2023-10-20 16:59:52,570 - modelscope - WARNING - No preprocessor field found in cfg.
2023-10-20 16:59:52,570 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-10-20 16:59:52,570 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': ' \.cache\\modelscope\\hub\\damo\\cv_unet_skin_retouching_torch'}. trying to build by task and model information.
2023-10-20 16:59:52,570 - modelscope - WARNING - Find task: skin-retouching-torch, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-10-20 16:59:54,204 - modelscope - INFO - Model revision not specified, use the latest revision: v2.0.2
2023-10-20 16:59:56,128 - modelscope - INFO - initiate model from  .cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface
2023-10-20 16:59:56,129 - modelscope - INFO - initiate model from location  .cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface.
2023-10-20 16:59:56,131 - modelscope - WARNING - No preprocessor field found in cfg.
2023-10-20 16:59:56,131 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-10-20 16:59:56,131 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': ' \.cache\\modelscope\\hub\\damo\\cv_resnet50_face-detection_retinaface'}. trying to build by task and model information.
2023-10-20 16:59:56,131 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-10-20 16:59:56,132 - modelscope - INFO - loading model from  .cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface\pytorch_model.pt
2023-10-20 16:59:56,447 - modelscope - INFO - load model done
2023-10-20 16:59:57.6041213 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2649'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6060098 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2644'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6079195 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2647'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6095857 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2658'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6111913 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2648'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6129316 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2657'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6146444 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2653'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6162097 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2652'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6178932 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2645'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6195050 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2643'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6211222 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2641'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6227551 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2633'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6244364 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2632'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6260385 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2624'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6279472 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2614'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6295474 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2613'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6311943 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2606'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6328114 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2598'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6344306 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2596'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:57.6360356 [W:onnxruntime:, graph.cc:3543 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer 'const_fold_opt__2594'. It is not used by any node and should be removed from the model.
2023-10-20 16:59:59,909 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-10-20 17:00:00,378 - modelscope - INFO - initiate model from  .cache\modelscope\hub\damo\cv_gpen_image-portrait-enhancement
2023-10-20 17:00:00,378 - modelscope - INFO - initiate model from location  .cache\modelscope\hub\damo\cv_gpen_image-portrait-enhancement.
2023-10-20 17:00:00,379 - modelscope - INFO - initialize model from  .cache\modelscope\hub\damo\cv_gpen_image-portrait-enhancement
Loading ResNet ArcFace
2023-10-20 17:00:02,250 - modelscope - INFO - load face enhancer model done
2023-10-20 17:00:02,522 - modelscope - INFO - load face detector model done
2023-10-20 17:00:02,765 - modelscope - INFO - load sr model done
2023-10-20 17:00:03,455 - modelscope - INFO - load fqa model done
  0%|                                                                                           | 0/13 [00:00<?, ?it/s]ERROR:root:Photo detect and count score error, error info: index 0 is out of bounds for axis 0 with size 0
  8%|██████▍                                                                            | 1/13 [00:00<00:09,  1.21it/s]2023-10-20 17:00:04,357 - modelscope - WARNING - task skin-retouching-torch input definition is missing
2023-10-20 17:00:05,845 - modelscope - WARNING - task skin-retouching-torch output keys are missing
2023-10-20 17:00:05,850 - modelscope - WARNING - task face_recognition input definition is missing
2023-10-20 17:00:06,010 - modelscope - INFO - model inference done
2023-10-20 17:00:06,010 - modelscope - WARNING - task face_recognition output keys are missing
 15%|████████████▊                                                                      | 2/13 [00:02<00:14,  1.34s/it]Face size in 10.jpg is small than 128. Ignore it.
2023-10-20 17:00:06,740 - modelscope - INFO - model inference done
 31%|█████████████████████████▌                                                         | 4/13 [00:03<00:06,  1.37it/s]Face size in 12.jpg is small than 128. Ignore it.
2023-10-20 17:00:07,470 - modelscope - INFO - model inference done
 46%|██████████████████████████████████████▎                                            | 6/13 [00:03<00:03,  1.79it/s]Face size in 3.jpg is small than 128. Ignore it.
ERROR:root:Photo detect and count score error, error info: index 0 is out of bounds for axis 0 with size 0
2023-10-20 17:00:08,156 - modelscope - INFO - model inference done
 69%|█████████████████████████████████████████████████████████▍                         | 9/13 [00:04<00:01,  2.55it/s]ERROR:root:Photo detect and count score error, error info: index 0 is out of bounds for axis 0 with size 0
Face size in 7.jpg is small than 128. Ignore it.
2023-10-20 17:00:08,922 - modelscope - INFO - model inference done
 92%|███████████████████████████████████████████████████████████████████████████▋      | 12/13 [00:05<00:00,  2.99it/s]ERROR:root:Photo detect and count score error, error info: index 0 is out of bounds for axis 0 with size 0
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:05<00:00,  2.37it/s]
selected paths: D:\AI\a1111\outputs/easyphoto-user-id-infos\sdfsdfpp\original_backup\5.jpg total scores:  0.739092085581511 face angles 0.9974882065198483
selected paths: D:\AI\a1111\outputs/easyphoto-user-id-infos\sdfsdfpp\original_backup\1.jpg total scores:  0.7270870034350126 face angles 0.9870332907040381
selected paths: D:\AI\a1111\outputs/easyphoto-user-id-infos\sdfsdfpp\original_backup\8.jpg total scores:  0.6434791298496579 face angles 0.9292798932098882
selected paths: D:\AI\a1111\outputs/easyphoto-user-id-infos\sdfsdfpp\original_backup\11.jpg total scores:  0.6193333629603326 face angles 0.8396072455471568
selected paths: D:\AI\a1111\outputs/easyphoto-user-id-infos\sdfsdfpp\original_backup\2.jpg total scores:  0.5224830993198278 face angles 0.7966540007810581
jpg: 5.jpg face_id_scores 0.739092085581511
jpg: 11.jpg face_id_scores 0.6193333629603326
jpg: 1.jpg face_id_scores 0.7270870034350126
jpg: 8.jpg face_id_scores 0.6434791298496579
jpg: 2.jpg face_id_scores 0.5224830993198278
0it [00:00, ?it/s]2023-10-20 17:00:12,763 - modelscope - WARNING - task semantic-segmentation input definition is missing
5it [00:05,  1.03s/it]
save processed image to D:\AI\a1111\outputs/easyphoto-user-id-infos\sdfsdfpp\processed_images\train\0.jpg
save processed image to D:\AI\a1111\outputs/easyphoto-user-id-infos\sdfsdfpp\processed_images\train\1.jpg
save processed image to D:\AI\a1111\outputs/easyphoto-user-id-infos\sdfsdfpp\processed_images\train\2.jpg
save processed image to D:\AI\a1111\outputs/easyphoto-user-id-infos\sdfsdfpp\processed_images\train\3.jpg
save processed image to D:\AI\a1111\outputs/easyphoto-user-id-infos\sdfsdfpp\processed_images\train\4.jpg
train_file_path :  D:\AI\a1111\extensions\sd-webui-EasyPhoto\scripts\train_kohya/train_lora.py
cache_log_file_path: D:\AI\a1111\outputs/easyphoto-tmp/train_kohya_log.txt
Traceback (most recent call last):
  File " AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File " AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AI\a1111\venv\lib\site-packages\accelerate\commands\launch.py", line 989, in <module>
    main()
  File "D:\AI\a1111\venv\lib\site-packages\accelerate\commands\launch.py", line 985, in main
    launch_command(args)
  File "D:\AI\a1111\venv\lib\site-packages\accelerate\commands\launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "D:\AI\a1111\venv\lib\site-packages\accelerate\commands\launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "D:\AI\a1111\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 72, in load_config_from_file    return config_class.from_yaml_file(yaml_file=config_file)
  File "D:\AI\a1111\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'
Error executing the command: Command '['D:\\AI\\a1111\\venv\\Scripts\\python.exe', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', 'D:\\AI\\a1111\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\sdfsdfpp\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\sdfsdfpp\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\sdfsdfpp\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=sdfsdfpp', '--cache_log_file=D:\\AI\\a1111\\outputs/easyphoto-tmp/train_kohya_log.txt', '--validation']' returned non-zero exit status 1.

**Comment by pdshwc** [comment]
same question

**Comment by wuziheng** [comment]
@belenkoksas  same with https://github.com/aigc-apps/sd-webui-EasyPhoto/issues/197
disscuss at ISSUE197
