### ISSUE TITLE
在生成人像时人脸周围和嘴唇、眼睛会有个黑框

### ISSUE THREAD

**Issue by cooffer** [aigc-apps/sd-webui-EasyPhoto#196]
我按照[https://github.com/aigc-apps/sd-webui-EasyPhoto/issues/177](issues177) 修改了之后，还是不行，生成出来的图片还是有黑框
下面是生成图片：
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/47267126/4a993456-7724-4acc-9863-46f01ba817a9)

这个是训练参数：
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/47267126/9b9dacbb-c918-49df-8cb1-060316a5adc1)

这个是生成参数：
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/47267126/62b08496-bdb3-40a6-a556-833f939fd369)
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/47267126/dd5df984-7bc7-47cd-ad4a-43143daaaf49)

**Comment by wuziheng** [comment]
1. 这个问题应该不是100%出现吧
2. 这个问题的原理应该是第二次生成的时候除了NSFW的内容变成黑色了，然后贴回去的就错了。

我的建议用一些安全的模板图和prompt 再试试？

**Comment by cooffer** [comment]
> 1. 这个问题应该不是100%出现吧
> 2. 这个问题的原理应该是第二次生成的时候除了NSFW的内容变成黑色了，然后贴回去的就错了。
> 
> 我的建议用一些安全的模板图和prompt 再试试？

在我电脑上几乎是必现的，我用的模型是这个：Chilloutmix-Ni-pruned-fp16-fix.safetensors，训练参数就是上面图片一样，生成参数也是和上面图片一样，并且第一次生成之后，使用同样的参数再次生成会报错：
Traceback (most recent call last):
  File "E:\AI\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 565, in easyphoto_infer_forward
    face_skin_mask = np.float32(face_skin(first_diffusion_output_image_crop, retinaface_detection, needs_index=[[1, 2, 3, 4, 5, 10, 11, 12, 13]])[0])
  File "E:\AI\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\face_process_utils.py", line 516, in __call__
    retinaface_box = retinaface_boxes[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
2023-10-23 13:45:18,383 - scripts - Template 1 error: Error info is index 0 is out of bounds for axis 0 with size 0, skip it.

下面是我的webui以及各组件版本：
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/47267126/fb1d31e5-f9eb-47c7-bd82-63171921d161)

下面是我已经安装的扩展：
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/47267126/b3f25c62-f7d0-4b42-8090-2014d4bbe133)

**Comment by wuziheng** [comment]
1.如果你方便调试代码，可以在easyphoto_infer.py中的每一次调用模型操作图片后，存下图片，从而debug相关黑色色块具体是由那个区域引入的。
2. File "E:\AI\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\face_process_utils.py", line 513, in call
retinaface_box = retinaface_boxes[0]
IndexError: index 0 is out of bounds for axis 0 with size 0 这一段显示的是你的人脸没有检测出来。而565 行是第一次diffusion model的地方，推测可能第一次就生成了黑色内容。

综上，是否可以尝试不要在sdxl 的图片里面生成，而是去普通模板验证一下链路是否有问题。

**Comment by wuziheng** [comment]
@cooffer 
类似这个PR https://github.com/aigc-apps/sd-webui-EasyPhoto/pull/193/files
你在里面搜索所有的debug ，打开那些注释，就可以保存中间图片

**Comment by cooffer** [comment]
> 1.如果你方便调试代码，可以在easyphoto_infer.py中的每一次调用模型操作图片后，存下图片，从而调试相关黑色色块具体是由那个区域引入的。 2. 文件 “E：\AI\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\face_process_utils.py”，第 513 行，在调用中 retinaface_box = retinaface_boxes[0] 索引错误：索引 0 超出大小为 0 的轴 0 的界限 这一段显示的是你的人脸没有检测出来。而565 行是第一次扩散模型的地方，推测可能第一次就生成了黑色内容。
> 
> 综上，是否可以尝试不要在sdxl 的图片里面生成，而是去普通模板验证一下链路是否有问题。

这个我尝试了在普通模型生成，也是一样的结果

**Comment by cooffer** [comment]
> 类似这个PR https://github.com/aigc-apps/sd-webui-EasyPhoto/pull/193/files 你在里面搜索所有的调试 ，打开那些注释，就可以保存中间图片

我可以试着debug一下，感谢
