### ISSUE TITLE
Linux cpu的机器部署训练报错

### ISSUE THREAD

**Issue by zhxd163** [aigc-apps/sd-webui-EasyPhoto#227]
train_file_path :  /data1/minisearch/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py
cache_log_file_path: /data1/minisearch/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt
2023-11-01 14:48:41.836939: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `0`
        `--num_machines` was set to a value of `1`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2023-11-01 14:48:47.008791: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-01 14:48:49,400 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-11-01 14:48:49,402 - modelscope - INFO - TensorFlow version 2.14.0 Found.
2023-11-01 14:48:49,406 - modelscope - INFO - Loading ast index from /data1/minisearch/stable-diffusion-webui/models/modelscope/ast_indexer
2023-11-01 14:48:49,439 - modelscope - INFO - Loading done! Current index file version is 1.9.3, with md5 9cdf950c42d23c714d2b20266e4a9321 and a total number of 943 components indexed
FATAL ERROR: NVIDIA Management Library (NVML) not found.
HINT: The NVIDIA Management Library ships with the NVIDIA display driver (available at
      https://www.nvidia.com/Download/index.aspx), or can be downloaded as part of the
      NVIDIA CUDA Toolkit (available at https://developer.nvidia.com/cuda-downloads).
      The lists of OS platforms and NVIDIA-GPUs supported by the NVML library can be
      found in the NVML API Reference at https://docs.nvidia.com/deploy/nvml-api.
11/01/2023 14:48:50 - INFO - __main__ - Distributed environment: DistributedType.NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: fp16

{'dynamic_thresholding_ratio', 'variance_type', 'prediction_type', 'thresholding', 'clip_sample_range', 'timestep_spacing', 'sample_max_value'} was not found in config. Values will be initialized to default values.
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
create LoRA network. base dim (rank): 128, alpha: 64
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
Downloading and preparing dataset imagefolder/default to /root/.cache/huggingface/datasets/imagefolder/default-0d7eed8ccc9e348c/0.0.0/37fbb85cc714a338bea574ac6c7d0b5be5aff46c1862c1989b20e0771199e93f...
Downloading data files: 100%|██████████| 7/7 [00:00<00:00, 33592.82it/s]
Downloading data files: 100%|██████████| 6/6 [00:00<00:00, 54827.50it/s]
Extracting data files: 100%|██████████| 6/6 [00:00<00:00, 2145.97it/s]
Dataset imagefolder downloaded and prepared to /root/.cache/huggingface/datasets/imagefolder/default-0d7eed8ccc9e348c/0.0.0/37fbb85cc714a338bea574ac6c7d0b5be5aff46c1862c1989b20e0771199e93f. Subsequent calls will reuse this data.
100%|██████████| 1/1 [00:00<00:00, 476.95it/s]
11/01/2023 14:49:07 - INFO - __main__ - ***** Running training *****
11/01/2023 14:49:07 - INFO - __main__ -   Num examples = 6
11/01/2023 14:49:07 - INFO - __main__ -   Num Epochs = 400
11/01/2023 14:49:07 - INFO - __main__ -   Instantaneous batch size per device = 1
11/01/2023 14:49:07 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 4
11/01/2023 14:49:07 - INFO - __main__ -   Gradient Accumulation steps = 4
11/01/2023 14:49:07 - INFO - __main__ -   Total optimization steps = 800
Steps:   0%|          | 0/800 [00:00<?, ?it/s]2023-11-01 14:49:07,743 - modelscope - INFO - Model revision not specified, use revision: v2.0.2
2023-11-01 14:49:10,194 - modelscope - INFO - initiate model from /data1/minisearch/stable-diffusion-webui/models/modelscope/hub/damo/cv_resnet50_face-detection_retinaface
2023-11-01 14:49:10,194 - modelscope - INFO - initiate model from location /data1/minisearch/stable-diffusion-webui/models/modelscope/hub/damo/cv_resnet50_face-detection_retinaface.
2023-11-01 14:49:10,224 - modelscope - WARNING - No preprocessor field found in cfg.
2023-11-01 14:49:10,224 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-11-01 14:49:10,224 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': '/data1/minisearch/stable-diffusion-webui/models/modelscope/hub/damo/cv_resnet50_face-detection_retinaface'}. trying to build by task and model information.
2023-11-01 14:49:10,224 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-11-01 14:49:10,226 - modelscope - INFO - cuda is not available, using cpu instead.
2023-11-01 14:49:10,226 - modelscope - INFO - loading model from /data1/minisearch/stable-diffusion-webui/models/modelscope/hub/damo/cv_resnet50_face-detection_retinaface/pytorch_model.pt
/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
2023-11-01 14:49:10,774 - modelscope - INFO - load model done
Insufficient data for plotting.
Traceback (most recent call last):
  File "/data1/minisearch/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py", line 1467, in <module>
    main()
  File "/data1/minisearch/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/utils/gpu_info.py", line 173, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/data1/minisearch/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py", line 1225, in main
    latents = vae.encode(batch["pixel_values"].to(dtype=weight_dtype)).latent_dist.sample()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/diffusers/models/autoencoder_kl.py", line 236, in encode
    h = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/diffusers/models/vae.py", line 110, in forward
    sample = self.conv_in(sample)
             ^^^^^^^^^^^^^^^^^^^^
  File "/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Steps:   0%|          | 0/800 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 989, in <module>
    main()
  File "/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 985, in main
    launch_command(args)
  File "/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/data1/minisearch/stable-diffusion-webui/venv/lib/python3.11/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/data1/minisearch/stable-diffusion-webui/venv/bin/python3', '/data1/minisearch/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py', '--pretrained_model_name_or_path=/data1/minisearch/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', '--pretrained_model_ckpt=/data1/minisearch/stable-diffusion-webui/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=/data1/minisearch/stable-diffusion-webui/outputs/easyphoto-user-id-infos/6/processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=16', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=/data1/minisearch/stable-diffusion-webui/outputs/easyphoto-user-id-infos/6/user_weights', '--logging_dir=/data1/minisearch/stable-diffusion-webui/outputs/easyphoto-user-id-infos/6/user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=/data1/minisearch/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=6', '--cache_log_file=/data1/minisearch/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt', '--validation']' returned non-zero exit status 1.
Error executing the command: Command '['/data1/minisearch/stable-diffusion-webui/venv/bin/python3', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', '/data1/minisearch/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py', '--pretrained_model_name_or_path=/data1/minisearch/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', '--pretrained_model_ckpt=/data1/minisearch/stable-diffusion-webui/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=/data1/minisearch/stable-diffusion-webui/outputs/easyphoto-user-id-infos/6/processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=16', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=/data1/minisearch/stable-diffusion-webui/outputs/easyphoto-user-id-infos/6/user_weights', '--logging_dir=/data1/minisearch/stable-diffusion-webui/outputs/easyphoto-user-id-infos/6/user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=/data1/minisearch/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=6', '--cache_log_file=/data1/minisearch/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt', '--validation']' returned non-zero exit status 1.

**Comment by wuziheng** [comment]
似乎是因为我们的模型推理走的是半精度，然后cpu版本没有这个支持，你需要去手动修改模型的load ，load全精度，才可能支持cpu，但这样估计比较慢。

**Comment by wuziheng** [comment]
其次有一些modelscope的模型似乎 都不支持cpu，我们不能保证整个推理链路在cpu上可以跑通。

**Comment by wuziheng** [comment]
请使用GPU 机器进行EasyPhoto的训练和推理。
