### ISSUE TITLE
error can't generation, face_id_retinaface_box= _face_id_retinaface_boxes[0] IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by aod109** [aigc-apps/sd-webui-EasyPhoto#238]
![error generated](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/76223323/250ae125-b993-450a-8fa4-1793ebb05194)

**Comment by wuziheng** [comment]
It seems your template image. or  SDXL-Beta generate image doesn't contain any face (to be detected)

**Comment by aod109** [comment]
What to do? should I retrain?

**Comment by wuziheng** [comment]
> What to do? should I retrain?

to use a template image with a certain face

**Comment by kangweihao** [comment]
我也遇到了这个问题，无论是使用模板的证件照还是文生图都遇到了这个问题
Loading weights [7c819b6d13] from D:\aaasd-webui-aki-v4.5\sd-webui-aki-v4.5\models\Stable-diffusion\majicmixRealistic_v7.safetensors
2023-12-21 19:44:01,992 - scripts - ControlNet unit number: 4
2Loading ResNet ArcFace
Loading VAE weights specified in settings: D:\aaasd-webui-aki-v4.5\sd-webui-aki-v4.5\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
VAE weights loaded.
Restoring base VAE
Applying attention optimization: xformers... done.
VAE weights loaded.
Traceback (most recent call last):
  File "D:\aaasd-webui-aki-v4.5\sd-webui-aki-v4.5\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\aaasd-webui-aki-v4.5\sd-webui-aki-v4.5\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\aaasd-webui-aki-v4.5\sd-webui-aki-v4.5\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\aaasd-webui-aki-v4.5\sd-webui-aki-v4.5\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\aaasd-webui-aki-v4.5\sd-webui-aki-v4.5\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\aaasd-webui-aki-v4.5\sd-webui-aki-v4.5\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\aaasd-webui-aki-v4.5\sd-webui-aki-v4.5\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\aaasd-webui-aki-v4.5\sd-webui-aki-v4.5\python\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "D:\aaasd-webui-aki-v4.5\sd-webui-aki-v4.5\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 918, in easyphoto_infer_forward
    _face_id_retinaface_box = _face_id_retinaface_boxes[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
