### ISSUE TITLE
The "EasyPhoto" tab is not appearing after success installation

### ISSUE THREAD

**Issue by unicornboat** [aigc-apps/sd-webui-EasyPhoto#239]
I run sd webui on my local machine. Controlnet is installed and used for ages. I installed the EasyPhoto via github link and I can see it appearing in the "installed" window under the "Extensions" tab.
Restarted the webui (soft restart and hard restart) but still can't see the "EastPhoto" tab.

**Comment by wuziheng** [comment]
Make sure install success, provide your terminal LOG when SDWebUI starts

**Comment by unicornboat** [comment]
Here's my log. It looks like the tensorflow-cpu spec is not reachable. I'm using Apple silicon M2 and have tensorflow for mac installed.
```
*** Error running install.py for extension /Users/it6/stable-diffision-webui/extensions/sd-webui-EasyPhoto.
*** Command: "/Users/it6/miniconda3/envs/sd/bin/python3.10" "/Users/it6/stable-diffision-webui/extensions/sd-webui-EasyPhoto/install.py"
*** Error code: 1
*** stdout: is_installed check for tensorflow-cpu failed as 'spec is None'
*** Installing requirements for easyphoto-webui
*** Installing requirements for tensorflow
*** 
*** stderr: Traceback (most recent call last):
***   File "/Users/it6/stable-diffision-webui/extensions/sd-webui-EasyPhoto/install.py", line 56, in <module>
***     launch.run_pip("install tensorflow-cpu", "requirements for tensorflow")
***   File "/Users/it6/stable-diffision-webui/modules/launch_utils.py", line 138, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "/Users/it6/stable-diffision-webui/modules/launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install requirements for tensorflow.
*** Command: "/Users/it6/miniconda3/envs/sd/bin/python3.10" -m pip install tensorflow-cpu --prefer-binary
*** Error code: 1
*** stderr: ERROR: Could not find a version that satisfies the requirement tensorflow-cpu (from versions: none)
*** ERROR: No matching distribution found for tensorflow-cpu
*** 
```

**Comment by wuziheng** [comment]
Sorry， we donot support MAC for now， please try on cloud nvidia gpu
