### ISSUE TITLE
生成时出现错误，controlnet错误

### ISSUE THREAD

**Issue by heroki0817** [aigc-apps/sd-webui-EasyPhoto#241]
感谢提供使用，目前在训练特定人物后，在生成过程中出现错误，但未影响生成结果。只是不知道为什么出错，controlnet版本为最新的

2023-11-07 19:44:38,326 - scripts - Start resize image from (610, 738) to (930, 1126).
2023-11-07 19:44:38,337 - scripts - Start face detect.
2023-11-07 19:44:51,936 - scripts - Start First diffusion.
*** Error running process: G:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "G:\sd-webui-aki-v4\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "G:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "G:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "G:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "G:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "G:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 339, in build_control_model
        raise RuntimeError(f"model not found: {model}")
    RuntimeError: model not found: None
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---

**Comment by wuziheng** [comment]
如果是aki，可以考虑更新到4.4

**Comment by wuziheng** [comment]
不知道是否已解决，该问题，一般是由于aki 4里面sdwebui的版本没有对齐导致。

**Comment by coolmian** [comment]
> 如果是aki，可以考虑更新到4.4

我也遇到这个问题了，请问4.4是指什么的版本？

**Comment by coolmian** [comment]
> 不知道是否已解决，该问题，一般是由于aki 4里面sdwebui的版本没有对齐导致。

版本没有对齐是什么意思？

**Comment by wuziheng** [comment]
> > 不知道是否已解决，该问题，一般是由于aki 4里面sdwebui的版本没有对齐导致。
> 
> 版本没有对齐是什么意思？

aki4.4 或者 sdwebui1.6
