### ISSUE TITLE
無法於Tab上顯示EasyPhoto

### ISSUE THREAD

**Issue by vclin123** [aigc-apps/sd-webui-EasyPhoto#270]
本來運行順利，不知道從哪時候開始，重新啟動WebUI之後，就無法於Tab上顯示EasyPhoto。啟動訊息出現錯誤如下，不知道怎麼解決，

*** Error loading script: api.py
    Traceback (most recent call last):
      File "E:\AI\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\api.py", line 6, in <module>
        from scripts.easyphoto_infer import *
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 40, in <module>
        from scripts.sdwebui import (ControlNetUnit, get_checkpoint_type,
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 23, in <module>
        from scripts.animatediff_utils import AnimateDiffProcess, motion_module
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\animatediff_utils.py", line 32, in <module>
        from modules.sd_samplers_common import (approximation_indexes,
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (E:\AI\modules\sd_samplers_common.py)

---
*** Error loading script: easyphoto_infer.py
    Traceback (most recent call last):
      File "E:\AI\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 40, in <module>
        from scripts.sdwebui import (ControlNetUnit, get_checkpoint_type,
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 23, in <module>
        from scripts.animatediff_utils import AnimateDiffProcess, motion_module
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\animatediff_utils.py", line 32, in <module>
        from modules.sd_samplers_common import (approximation_indexes,
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (E:\AI\modules\sd_samplers_common.py)

---
*** Error loading script: easyphoto_train.py
    Traceback (most recent call last):
      File "E:\AI\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\easyphoto_train.py", line 21, in <module>
        from scripts.sdwebui import get_checkpoint_type, unload_sd
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 23, in <module>
        from scripts.animatediff_utils import AnimateDiffProcess, motion_module
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\animatediff_utils.py", line 32, in <module>
        from modules.sd_samplers_common import (approximation_indexes,
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (E:\AI\modules\sd_samplers_common.py)

---
*** Error loading script: easyphoto_ui.py
    Traceback (most recent call last):
      File "E:\AI\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\easyphoto_ui.py", line 14, in <module>
        from scripts.easyphoto_infer import (easyphoto_infer_forward,
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 40, in <module>
        from scripts.sdwebui import (ControlNetUnit, get_checkpoint_type,
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 23, in <module>
        from scripts.animatediff_utils import AnimateDiffProcess, motion_module
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\animatediff_utils.py", line 32, in <module>
        from modules.sd_samplers_common import (approximation_indexes,
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (E:\AI\modules\sd_samplers_common.py)

---
*** Error loading script: easyphoto_utils.py
    Traceback (most recent call last):
      File "E:\AI\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\easyphoto_utils.py", line 13, in <module>
        import scripts.easyphoto_infer
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 40, in <module>
        from scripts.sdwebui import (ControlNetUnit, get_checkpoint_type,
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 23, in <module>
        from scripts.animatediff_utils import AnimateDiffProcess, motion_module
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\animatediff_utils.py", line 32, in <module>
        from modules.sd_samplers_common import (approximation_indexes,
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (E:\AI\modules\sd_samplers_common.py)

---
*** Error loading script: sdwebui.py
    Traceback (most recent call last):
      File "E:\AI\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 23, in <module>
        from scripts.animatediff_utils import AnimateDiffProcess, motion_module
      File "E:\AI\extensions\sd-webui-EasyPhoto\scripts\animatediff_utils.py", line 32, in <module>
        from modules.sd_samplers_common import (approximation_indexes,
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (E:\AI\modules\sd_samplers_common.py)

**Comment by hkpD** [comment]
Hello, I was getting same errors because I made changes to the "EasyPhoto" files. Have you made any changes to the EasyPhoto extension files? I recommend you delete the folder and "git pull" a new EasyPhoto. That was my resolution

**Comment by yinglee712** [comment]
最新的版本添加了一个用正脸辅助生成的新功能，但这个功能要求更高版本的xformers，我猜可能是这个原因；

我这里本地端显示但用不了最新版本的easyphoto，云端升级版本之后干脆直接不显示easyphoto的UI，重新安装也没用；退回上个版本就可以；以下or

1，用旧版本的easyphoto；
2，升级xFormers的版本；
3，等待作者们这周对兼容性的更新；（有人提出了相关的问题，而且有作者回复了）

**Comment by wuziheng** [comment]
1. 确认一下你重新启动之前是否已经安装了带有animatediff 版本的EasyPhoto
2. 确认一下你的sdwebui的版本
@bubbliiiing  能确认一下这个需要升级到哪个版本么的sdwebui 才可以正确import么

**Comment by bubbliiiing** [comment]
麻烦拉取最新的代码，现在会进行错误的catch，尽管旧版本的webui不能使用Video inference，但不影响Photo inference的功能。

**Comment by vclin123** [comment]
> 您好，我不確定是否相關，但我遇到了類似的錯誤，因為我對“EasyPhoto”文件進行了更改。您是否對 EasyPhoto 擴充功能進行過任何更改？我建議您刪除該資料夾並“git pull”一個新的 EasyPhoto。這就是我的決心

感謝您，昨日EasyPhoto有更新，重新下載OK了

**Comment by vclin123** [comment]
> 麻煩拉取最新的程式碼，現在會進行錯誤的catch，雖然舊版的webui不能使用影片推理，但不影響照片推理的功能。

感謝您，昨日EasyPhoto有更新，重新下載OK了

**Comment by vclin123** [comment]
> 1. 確認一下你重新啟動之前是否已經安裝了帶有animatediff版本的EasyPhoto
> 2. 確認一下您的 sdwebui 的版本
>    @bubbliiiing  能確認一下這個需要升級到哪個版本的sdwebui才可以正確導入嗎

感謝您，昨日EasyPhoto有更新，重新下載OK了

**Comment by vclin123** [comment]
> 最新的版本新增了一個用正臉輔助產生的新功能，但這個功能對xformers的版本要求更高，我猜可能是這個原因；
> 
> 我這裡本地端顯示但用不了最新版本的easyphoto，雲端升級版本之後乾脆直接不顯示easyphoto的UI，重新安裝也用；退回上個版本就可以；以下或者
> 
> 1，用舊版的easyphoto； 2，升級xFormers的版本； 3，等待作者們這週對兼容性的更新；（有人提出了相關的問題，並且有作者回復了）

感謝您，昨日EasyPhoto有更新，重新下載OK了
