### ISSUE TITLE
更新版本ID为9efad36之后没法正确运行推理，但是a722254一切正常；

### ISSUE THREAD

**Issue by yinglee712** [aigc-apps/sd-webui-EasyPhoto#272]
To create a public link, set `share=True` in `launch()`.
Startup time: 100.9s (prepare environment: 71.5s, import torch: 7.1s, import gradio: 1.2s, setup paths: 0.8s, initialize shared: 0.4s, other imports: 1.1s, setup codeformer: 0.1s, load scripts: 7.5s, create ui: 7.8s, gradio launch: 3.1s, app_started_callback: 0.2s).
No Image data blocks found.
No Image data blocks found.
2023-11-21 05:28:34,295 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\models\Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors : Hash match
2023-11-21 05:28:35,014 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\models\ControlNet/control_v11p_sd15_openpose.pth : Hash match
2023-11-21 05:28:35,561 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\models\ControlNet/control_v11p_sd15_canny.pth : Hash match
2023-11-21 05:28:36,103 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\models\ControlNet/control_v11f1e_sd15_tile.pth : Hash match
2023-11-21 05:28:36,626 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\models\ControlNet/control_sd15_random_color.pth : Hash match
2023-11-21 05:28:37,162 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\models\Lora/FilmVelvia3.safetensors : Hash match
2023-11-21 05:28:37,735 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator/downloads/openpose\body_pose_model.pth : Hash match
2023-11-21 05:28:38,305 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator/downloads/openpose\facenet.pth : Hash match
2023-11-21 05:28:38,836 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator/downloads/openpose\hand_pose_model.pth : Hash match
2023-11-21 05:28:39,363 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\models\VAE/vae-ft-mse-840000-ema-pruned.ckpt : Hash match
2023-11-21 05:28:39,948 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\models\face_skin.pth : Hash match
2023-11-21 05:28:40,576 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\models\face_landmarks.pth : Hash match
2023-11-21 05:28:41,174 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\models\makeup_transfer.pth : Hash match
2023-11-21 05:28:41,719 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\models\training_templates\1.jpg : Hash match
2023-11-21 05:28:42,250 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\models\training_templates\2.jpg : Hash match
2023-11-21 05:28:42,802 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\models\training_templates\3.jpg : Hash match
2023-11-21 05:28:43,326 - scripts - L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\models\training_templates\4.jpg : Hash match
Loading weights [e4a30e4607] from L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\models\Stable-diffusion\写实\majicmixRealistic_v6.safetensors
Traceback (most recent call last):
  File "L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "contextlib.py", line 79, in inner
  File "L:\V4\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 406, in easyphoto_infer_forward
    if shared.opts.data.get("control_net_unit_count") < max_control_net_unit_count:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

--------------------------------------------
发现easyphoto更新了，我马上在本地跟进版本，但发现推理的功能没法用了；

我把xFormers从0.017升到0.0.21了，似乎本非xformers版本的问题；

help!

**Comment by wuziheng** [comment]
看到了，这是由于我们更新了IPA后，会检查你的controlnet最大设置，如果数目不对则会报错。但似乎这个检查，出了问题。一个简单的方式是吧line 406 附近的代码注释掉。我们会让相关同学紧急修复一下。随时邀请你测试。

@hkunzhe 
似乎某些版本的sdwebui 没有这个get ，你需要先assert一下类型。

**Comment by hkunzhe** [comment]
@yinglee712, Can you please check if the sd-webui-controlnet is installed in the webui and what version of the plugin it is? The new feature IP-Adapter requires the latest controlnet plugin. 把 controlnet 插件升级到最新，然后重启 webui，看看这样还存在问题吗？

**Comment by hkunzhe** [comment]
closed as #274
