### ISSUE TITLE
生成图片是报：not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by zhuspace** [aigc-apps/sd-webui-EasyPhoto#273]
错误信息如下：
Loading weights [e6415c4892] from D:\git\SD\sd-webui-aki-v4.4\models\Stable-diffusion\真实系：realisticVisionV20_v20.safetensors
Traceback (most recent call last):
  File "D:\git\SD\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\git\SD\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\git\SD\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\git\SD\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\git\SD\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\git\SD\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\git\SD\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\git\SD\sd-webui-aki-v4.4\python\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "D:\git\SD\sd-webui-aki-v4.4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 406, in easyphoto_infer_forward
    if shared.opts.data.get("control_net_unit_count") < max_control_net_unit_count:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by bubbliiiing** [comment]
Fix Now
