### ISSUE TITLE
not enough memory

### ISSUE THREAD

**Issue by tangflash** [aigc-apps/sd-webui-EasyPhoto#28]
my memory is 32G,why has below error

2023-09-06 17:51:45,283 - ControlNet - INFO - ControlNet model control_v11p_sd15_openpose [cab727d4] loaded.
2023-09-06 17:51:45,373 - ControlNet - INFO - Loading preprocessor: openpose_full
2023-09-06 17:51:45,373 - ControlNet - INFO - preprocessor resolution = 512
2023-09-06 17:51:48,117 - ControlNet - INFO - Loading model: control_sd15_random_color [3afa6fba]
2023-09-06 17:51:49,487 - ControlNet - INFO - Loaded state_dict from [D:\sd15\stable-diffusion-webui\models\ControlNet\control_sd15_random_color.pth]
2023-09-06 17:51:49,487 - ControlNet - INFO - controlnet_default_config
*** Error running before_process_batch: D:\sd15\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\sd15\stable-diffusion-webui\modules\scripts.py", line 627, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "D:\sd15\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 972, in before_process_batch
        self.controlnet_main_entry(p)
      File "D:\sd15\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "D:\sd15\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "D:\sd15\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 350, in build_control_model
        network = build_model_by_guess(state_dict, unet, model_path)
      File "D:\sd15\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_model_guess.py", line 151, in build_model_by_guess
        p_new = p + unet_state_dict[key].clone().cpu()
    RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 671088640000 bytes.

---
100%|██████████████████████████████████████████████████████████████████████████████████| 23/23 [00:10<00:00,  2.27it/s]
Traceback (most recent call last):it/s]
  File "D:\sd15\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd15\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\sd15\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd15\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd15\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\sd15\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\sd15\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sd15\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 287, in easyphoto_infer_forward
    output_image = inpaint_with_mask_face(input_image, input_mask, replaced_input_image, diffusion_steps=first_diffusion_steps, denoising_strength=first_denoising_strength, input_prompt=input_prompt, hr_scale=1.0, seed=str(seed))
  File "D:\sd15\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 116, in inpaint_with_mask_face
    image = i2i_inpaint_call(
  File "D:\sd15\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 285, in i2i_inpaint_call
    h_1, w_1, c_1 = np.shape(processed.images[1])
IndexError: list index out of range

**Comment by tangflash** [comment]
thank you for your reply. I restart my computer.it is ok now. I think sdwebui has memory leak.

**Comment by tangflash** [comment]
I restart my computer.it is ok now. I think sdwebui has memory leak.
