### ISSUE TITLE
 RuntimeError: The size of tensor a (16) must match the size of tensor b (8) at non-singleton dimension 0

### ISSUE THREAD

**Issue by Yaohs1995** [aigc-apps/sd-webui-EasyPhoto#292]
when i update my project, sometimes raise the err

Traceback (most recent call last):
  File "stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 1868, in easyphoto_video_infer_forward
    input_image, loop_template_crop_safe_box = call_face_crop_templates(
  File "stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_utils/face_process_utils.py", line 221, in call_face_crop_templates
    raise ValueError("There is no face in video.")
ValueError: There is no face in video.

When the parameters are the same, sometimes it runs successfully and sometimes it fails

**Comment by wuziheng** [comment]
OK， it's a Bug, we first generate a video with face, but with inappropriate， it may generate video all frame contains no face, it may cause this bug, carefully use prompt and seed

**Comment by Yaohs1995** [comment]
I am using the default prompt words and have not made any modifications
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/73219327/9901f748-a0bb-4757-b008-fa0329cedb00)
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/73219327/3214cf91-f149-4ae5-a68c-9e494dd89056)
