### ISSUE TITLE
Failed to obtain Lora after training, please check the training process.

### ISSUE THREAD

**Issue by jiayev** [aigc-apps/sd-webui-EasyPhoto#293]
Traceback (most recent call last):
  File "D:\lyj\soft\anaconda3\envs\sd2\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\lyj\soft\anaconda3\envs\sd2\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\lyj\soft\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\launch.py", line 989, in <module>
    main()
  File "D:\lyj\soft\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\launch.py", line 985, in main
    launch_command(args)
  File "D:\lyj\soft\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "D:\lyj\soft\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "D:\lyj\soft\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "D:\lyj\soft\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\config\config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Error executing the command: Command '['D:\\lyj\\soft\\stable diffusion\\stable-diffusion-webui\\venv\\Scripts\\Python.exe', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', 'D:\\lyj\\soft\\stable diffusion\\stable-diffusion-webui\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora_sd_XL.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-xl\\stabilityai_stable_diffusion_xl_base_1.0', '--pretrained_model_ckpt=models\\Stable-diffusion\\leosamsHelloworldSDXL_helloworldSDXL20.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\lblian\\processed_images', '--caption_column=text', '--resolution=1024', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=600', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=32', '--network_alpha=16', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\lblian\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\lblian\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=lblian', '--cache_log_file=D:\\lyj\\soft\\stable diffusion\\stable-diffusion-webui\\outputs/easyphoto-tmp/train_kohya_log.txt', '--original_config=D:\\lyj\\soft\\stable diffusion\\stable-diffusion-webui\\repositories\\generative-models\\configs\\inference\\sd_xl_base.yaml', '--pretrained_vae_model_name_or_path=D:\\lyj\\soft\\stable diffusion\\stable-diffusion-webui\\extensions\\sd-webui-EasyPhoto\\models/stable-diffusion-xl\\madebyollin_sdxl_vae_fp16_fix']' returned non-zero exit status 1.

**Comment by wuziheng** [comment]
accelerate 版本问题，推荐去云平台开一个默认机器，跑起来，然后和自己的机器对比一下环境

**Comment by wuziheng** [comment]
主要对齐几个版本 sdwebui diffusers accelerate ，如果都对齐还有问题，我们可以持续跟进一下，然后你在issue 搜一下diffusers/accelerate 版本，有一些历史记录。
