### ISSUE TITLE
Failed to obtain Lora after training, please check the training process.

### ISSUE THREAD

**Issue by Vincent970317** [aigc-apps/sd-webui-EasyPhoto#299]
2023-12-02 19:37:35,620 - modelscope - INFO - PyTorch version 1.13.1+cu117 Found.
2023-12-02 19:37:35,628 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2023-12-02 19:37:35,628 - modelscope - INFO - Loading ast index from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\ast_indexer
2023-12-02 19:37:35,807 - modelscope - INFO - Loading done! Current index file version is 1.9.3, with md5 efeb64010e090f71681a625e0bbc0e08 and a total number of 943 components indexed
2023-12-02 19:37:44,605 - modelscope - INFO - Use user-specified model revision: v1.0.3
2023-12-02 19:37:45,051 - modelscope - WARNING - ('PIPELINES', 'face_recognition', 'face_recognition') not found in ast index file
2023-12-02 19:37:45,051 - modelscope - INFO - initiate model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\bubbliiiing\cv_retinafce_recognition
2023-12-02 19:37:45,051 - modelscope - INFO - initiate model from location D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\bubbliiiing\cv_retinafce_recognition.
2023-12-02 19:37:45,055 - modelscope - INFO - initialize model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\bubbliiiing\cv_retinafce_recognition
2023-12-02 19:37:45,083 - modelscope - WARNING - ('MODELS', 'face_recognition', 'face_recognition') not found in ast index file
2023-12-02 19:37:45,784 - modelscope - INFO - Model revision not specified, use revision: v2.0.2
2023-12-02 19:37:47,589 - modelscope - INFO - initiate model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface
2023-12-02 19:37:47,589 - modelscope - INFO - initiate model from location D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface.
2023-12-02 19:37:47,599 - modelscope - WARNING - No preprocessor field found in cfg.
2023-12-02 19:37:47,600 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-12-02 19:37:47,600 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'D:\\ai\\sd-webui-aki-v4.5\\.cache\\modelscope\\hub\\damo\\cv_resnet50_face-detection_retinaface'}. trying to build by task and model information.
2023-12-02 19:37:47,600 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-12-02 19:37:47,603 - modelscope - INFO - loading model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface\pytorch_model.pt
2023-12-02 19:37:49,304 - modelscope - INFO - load model done
2023-12-02 19:37:52,659 - modelscope - INFO - load facefusion models done
2023-12-02 19:37:52,659 - modelscope - INFO - init done
2023-12-02 19:37:52,667 - modelscope - WARNING - No preprocessor field found in cfg.
2023-12-02 19:37:52,667 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-12-02 19:37:52,667 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'D:\\ai\\sd-webui-aki-v4.5\\.cache\\modelscope\\hub\\bubbliiiing\\cv_retinafce_recognition'}. trying to build by task and model information.
2023-12-02 19:37:52,667 - modelscope - WARNING - No preprocessor key ('face_recognition', 'face_recognition') found in PREPROCESSOR_MAP, skip building preprocessor.
2023-12-02 19:37:52,670 - modelscope - INFO - image face recognition model init done
2023-12-02 19:37:53,383 - modelscope - INFO - Use user-specified model revision: v2.0.2
2023-12-02 19:37:55,139 - modelscope - INFO - initiate model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface
2023-12-02 19:37:55,139 - modelscope - INFO - initiate model from location D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface.
2023-12-02 19:37:55,150 - modelscope - WARNING - No preprocessor field found in cfg.
2023-12-02 19:37:55,151 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-12-02 19:37:55,151 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'D:\\ai\\sd-webui-aki-v4.5\\.cache\\modelscope\\hub\\damo\\cv_resnet50_face-detection_retinaface'}. trying to build by task and model information.
2023-12-02 19:37:55,151 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-12-02 19:37:55,154 - modelscope - INFO - loading model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface\pytorch_model.pt
2023-12-02 19:37:55,604 - modelscope - INFO - load model done
2023-12-02 19:37:56,331 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-12-02 19:37:56,692 - modelscope - INFO - initiate model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_u2net_salient-detection
2023-12-02 19:37:56,692 - modelscope - INFO - initiate model from location D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_u2net_salient-detection.
2023-12-02 19:37:56,696 - modelscope - INFO - initialize model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_u2net_salient-detection
2023-12-02 19:37:58,499 - modelscope - WARNING - No preprocessor field found in cfg.
2023-12-02 19:37:58,499 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-12-02 19:37:58,499 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'D:\\ai\\sd-webui-aki-v4.5\\.cache\\modelscope\\hub\\damo\\cv_u2net_salient-detection'}. trying to build by task and model information.
2023-12-02 19:37:58,499 - modelscope - WARNING - No preprocessor key ('detection', 'semantic-segmentation') found in PREPROCESSOR_MAP, skip building preprocessor.
2023-12-02 19:37:59,251 - modelscope - INFO - Use user-specified model revision: v1.0.2
2023-12-02 19:38:00,005 - modelscope - WARNING - ('PIPELINES', 'skin-retouching-torch', 'skin-retouching-torch') not found in ast index file
2023-12-02 19:38:00,005 - modelscope - INFO - initiate model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_unet_skin_retouching_torch
2023-12-02 19:38:00,005 - modelscope - INFO - initiate model from location D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_unet_skin_retouching_torch.
2023-12-02 19:38:00,015 - modelscope - WARNING - No preprocessor field found in cfg.
2023-12-02 19:38:00,015 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-12-02 19:38:00,016 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'D:\\ai\\sd-webui-aki-v4.5\\.cache\\modelscope\\hub\\damo\\cv_unet_skin_retouching_torch'}. trying to build by task and model information.
2023-12-02 19:38:00,016 - modelscope - WARNING - Find task: skin-retouching-torch, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-12-02 19:38:01,511 - modelscope - INFO - Model revision not specified, use revision: v2.0.2
2023-12-02 19:38:03,775 - modelscope - INFO - initiate model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface
2023-12-02 19:38:03,776 - modelscope - INFO - initiate model from location D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface.
2023-12-02 19:38:03,786 - modelscope - WARNING - No preprocessor field found in cfg.
2023-12-02 19:38:03,786 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-12-02 19:38:03,786 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'D:\\ai\\sd-webui-aki-v4.5\\.cache\\modelscope\\hub\\damo\\cv_resnet50_face-detection_retinaface'}. trying to build by task and model information.
2023-12-02 19:38:03,786 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-12-02 19:38:03,789 - modelscope - INFO - loading model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_resnet50_face-detection_retinaface\pytorch_model.pt
2023-12-02 19:38:04,258 - modelscope - INFO - load model done
2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 1 6 4 6 8   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 4 9 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 3 4 1 9 2   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 4 4 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 3 8 0 6 8   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 4 7 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 4 0 7 1 3   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 5 8 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 4 5 2 0 5   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 4 8 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 4 9 2 4 3   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 5 7 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 5 4 4 7 7   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 5 3 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 5 8 0 4 3   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 5 2 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 6 1 4 2 6   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 4 5 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 6 5 4 2 1   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 4 3 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 6 8 9 0 1   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 4 1 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 7 2 5 5 7   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 3 3 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 7 5 9 3 9   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 3 2 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 8 0 5 4 7   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 2 4 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 8 5 0 3 0   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 1 4 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 8 8 2 4 6   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 1 3 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 9 1 4 2 4   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 6 0 6 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 9 6 0 9 0   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 5 9 8 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 1 9 8 9 5 7   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 5 9 6 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2 0 2 3 - 1 2 - 0 2   1 9 : 3 8 : 0 9 . 8 2 0 1 8 5 8   [ W : o n n x r u n t i m e : ,   g r a p h . c c : 3 5 5 3   o n n x r u n t i m e : : G r a p h : : C l e a n U n u s e d I n i t i a l i z e r s A n d N o d e A r g s ]   R e m o v i n g   i n i t i a l i z e r   ' c o n s t _ f o l d _ o p t _ _ 2 5 9 4 ' .   I t   i s   n o t   u s e d   b y   a n y   n o d e   a n d   s h o u l d   b e   r e m o v e d   f r o m   t h e   m o d e l . 
 2023-12-02 19:38:10,875 - modelscope - INFO - Use user-specified model revision: v1.0.0
2023-12-02 19:38:11,330 - modelscope - INFO - initiate model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_gpen_image-portrait-enhancement
2023-12-02 19:38:11,330 - modelscope - INFO - initiate model from location D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_gpen_image-portrait-enhancement.
2023-12-02 19:38:11,334 - modelscope - INFO - initialize model from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\damo\cv_gpen_image-portrait-enhancement
Loading ResNet ArcFace
ERROR:root:Photo detect and count score error, error info: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
2023-12-02 19:38:28,640 - modelscope - WARNING - task skin-retouching-torch input definition is missing
2023-12-02 19:39:02,038 - modelscope - WARNING - task skin-retouching-torch output keys are missing
2023-12-02 19:39:02,104 - modelscope - WARNING - task face_recognition input definition is missing
2023-12-02 19:39:05,278 - modelscope - INFO - model inference done
2023-12-02 19:39:05,278 - modelscope - WARNING - task face_recognition output keys are missing
2023-12-02 19:39:10,983 - modelscope - INFO - model inference done
2023-12-02 19:39:16,253 - modelscope - INFO - model inference done
2023-12-02 19:39:21,519 - modelscope - INFO - model inference done
2023-12-02 19:39:26,874 - modelscope - INFO - model inference done
selected paths: D:\ai\sd-webui-aki-v4.5\outputs/easyphoto-user-id-infos\test13\original_backup\1.jpg total scores:  0.7722152263542765 face angles 0.9919016058644404
selected paths: D:\ai\sd-webui-aki-v4.5\outputs/easyphoto-user-id-infos\test13\original_backup\5.jpg total scores:  0.7659402640946812 face angles 0.9688061292201502
selected paths: D:\ai\sd-webui-aki-v4.5\outputs/easyphoto-user-id-infos\test13\original_backup\2.jpg total scores:  0.757668508603594 face angles 0.9513587990049577
selected paths: D:\ai\sd-webui-aki-v4.5\outputs/easyphoto-user-id-infos\test13\original_backup\3.jpg total scores:  0.7483179815321176 face angles 0.9720719641110714
selected paths: D:\ai\sd-webui-aki-v4.5\outputs/easyphoto-user-id-infos\test13\original_backup\4.jpg total scores:  0.6938633246469134 face angles 0.9317151352075952
jpg: 2.jpg face_id_scores 0.757668508603594
jpg: 5.jpg face_id_scores 0.7659402640946812
jpg: 1.jpg face_id_scores 0.7722152263542765
jpg: 3.jpg face_id_scores 0.7483179815321176
jpg: 4.jpg face_id_scores 0.6938633246469134
save processed image to D:\ai\sd-webui-aki-v4.5\outputs/easyphoto-user-id-infos\test13\processed_images\train\0.jpg
save processed image to D:\ai\sd-webui-aki-v4.5\outputs/easyphoto-user-id-infos\test13\processed_images\train\1.jpg
save processed image to D:\ai\sd-webui-aki-v4.5\outputs/easyphoto-user-id-infos\test13\processed_images\train\2.jpg
save processed image to D:\ai\sd-webui-aki-v4.5\outputs/easyphoto-user-id-infos\test13\processed_images\train\3.jpg
save processed image to D:\ai\sd-webui-aki-v4.5\outputs/easyphoto-user-id-infos\test13\processed_images\train\4.jpg
train_file_path :  D:\ai\sd-webui-aki-v4.5\extensions\sd-webui-EasyPhoto\scripts\train_kohya/train_lora.py
cache_log_file_path: D:\ai\sd-webui-aki-v4.5\outputs/easyphoto-tmp/train_kohya_log.txt
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2023-12-02 19:39:57.547368: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From D:\ai\sd-webui-aki-v4.5\python\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2023-12-02 19:40:09,343 - modelscope - INFO - PyTorch version 1.13.1+cu117 Found.
2023-12-02 19:40:09,349 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2023-12-02 19:40:09,349 - modelscope - INFO - Loading ast index from D:\ai\sd-webui-aki-v4.5\.cache\modelscope\hub\ast_indexer
2023-12-02 19:40:09,727 - modelscope - INFO - Loading done! Current index file version is 1.9.3, with md5 efeb64010e090f71681a625e0bbc0e08 and a total number of 943 components indexed
12/02/2023 19:40:11 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

{'prediction_type', 'clip_sample_range', 'variance_type', 'sample_max_value', 'dynamic_thresholding_ratio', 'thresholding', 'timestep_spacing'} was not found in config. Values will be initialized to default values.
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Traceback (most recent call last):
  File "D:\ai\sd-webui-aki-v4.5\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ai\sd-webui-aki-v4.5\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ai\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\commands\launch.py", line 989, in <module>
    main()
  File "D:\ai\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\commands\launch.py", line 985, in main
    launch_command(args)
  File "D:\ai\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\commands\launch.py", line 979, in launch_command
    simple_launcher(args)
  File "D:\ai\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\ai\\sd-webui-aki-v4.5\\python\\python.exe', 'D:\\ai\\sd-webui-aki-v4.5\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\test13\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\test13\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\test13\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=test13', '--cache_log_file=D:\\ai\\sd-webui-aki-v4.5\\outputs/easyphoto-tmp/train_kohya_log.txt', '--validation']' returned non-zero exit status 3221225478.
Error executing the command: Command '['D:\\ai\\sd-webui-aki-v4.5\\python\\python.exe', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', 'D:\\ai\\sd-webui-aki-v4.5\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\test13\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\test13\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\test13\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=test13', '--cache_log_file=D:\\ai\\sd-webui-aki-v4.5\\outputs/easyphoto-tmp/train_kohya_log.txt', '--validation']' returned non-zero exit status 1.
Using already loaded model epicrealism_pureEvolution.safetensors [62e2993f1d]: done in 0.0s

**Comment by Vincent970317** [comment]
[Diagnostics-1701517352.log](https://github.com/aigc-apps/sd-webui-EasyPhoto/files/13536161/Diagnostics-1701517352.log)
请问下问题在哪里呢，我搞了两天都没搞定

**Comment by bubbliiiing** [comment]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/47347516/0dc6c90c-7006-487c-bda9-0bbee868feb8)
pytorch版本太久了应该。

**Comment by Vincent970317** [comment]
好的，谢谢，我试试换下4.4的秋叶，然后还不行我再把train_kohya_log.txt传一下

**Comment by Vincent970317** [comment]
pytorch版本怎么换新的呢
