### ISSUE TITLE
多卡训练报错，sd已经指定--device-id=0，不清楚怎么办

### ISSUE THREAD

**Issue by JonSmall** [aigc-apps/sd-webui-EasyPhoto#300]
2023-12-04 12:36:06.179241: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-04 12:36:06.211890: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/envs/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/envs/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/envs/lib/python3.10/site-packages/accelerate/commands/launch.py", line 989, in <module>
    main()
  File "/home/envs/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in main
    launch_command(args)
  File "/home/envs/lib/python3.10/site-packages/accelerate/commands/launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/home/envs/lib/python3.10/site-packages/accelerate/commands/launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/envs/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/envs/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'

**Comment by hkunzhe** [comment]
@JonSmall Currently, we do not support multi-GPU training. Please specify the GPU by adding the CUDA_VISIBLE_DEVICES environment variable when launching the SD WebUI.
