### ISSUE TITLE
Failed to obtain Lora after training, please check the training process.

### ISSUE THREAD

**Issue by robitronathon** [aigc-apps/sd-webui-EasyPhoto#304]
train_file_path :  A:\ai\sd.webui\webui\extensions\sd-webui-EasyPhoto\scripts\train_kohya/train_lora.py
cache_log_file_path: A:\ai\sd.webui\webui\outputs/easyphoto-tmp/train_kohya_log.txt
2023-12-05 09:59:28.610772: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From A:\ai\sd.webui\system\python\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "A:\ai\sd.webui\system\python\lib\site-packages\accelerate\commands\launch.py", line 989, in <module>
    main()
  File "A:\ai\sd.webui\system\python\lib\site-packages\accelerate\commands\launch.py", line 985, in main
    launch_command(args)
  File "A:\ai\sd.webui\system\python\lib\site-packages\accelerate\commands\launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "A:\ai\sd.webui\system\python\lib\site-packages\accelerate\commands\launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "A:\ai\sd.webui\system\python\lib\site-packages\accelerate\commands\config\config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "A:\ai\sd.webui\system\python\lib\site-packages\accelerate\commands\config\config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'downcase_fp16'
Error executing the command: Command '['A:\\ai\\sd.webui\\system\\python\\python.exe', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', 'A:\\ai\\sd.webui\\webui\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\ryn\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\ryn\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\ryn\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=ryn', '--cache_log_file=A:\\ai\\sd.webui\\webui\\outputs/easyphoto-tmp/train_kohya_log.txt']' returned non-zero exit status 1.
Using already loaded model default gotcha 70 ani15 30.fp16.safetensors [12ea226f45]: done in 1.4s (send model to device: 1.4s)

**Comment by wuziheng** [comment]
确认一下你的accelerate 和diffusers 还有xformers的版本，似乎不是代码的问题。
