### ISSUE TITLE
ailiyun DSW  case does not work as expected

### ISSUE THREAD

**Issue by t00350320** [aigc-apps/sd-webui-EasyPhoto#305]
https://help.aliyun.com/document_detail/2567864.html
```
! cd stable-diffusion-webui && python launch.py --no-half-vae --xformers
Traceback (most recent call last):
  File "launch.py", line 1, in <module>
    from modules import launch_utils
  File "/opt/conda/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg/modules/__init__.py", line 12, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/opt/conda/lib/python3.8/site-packages/MultiScaleDeformableAttention-1.0-py3.8-linux-x86_64.egg/modules/ms_deform_attn.py", line 21, in <module>
    from ..functions import MSDeformAttnFunction
ValueError: attempted relative import beyond top-level package
```

**Comment by zouxinyi0625** [comment]
Make sure you have choose the correct image:  stable-diffusion-webui-develop:1.0.0-pytorch2.01-gpu-py310-cu117-ubuntu22.04

See demo here: https://gallery.pai-ml.com/#/preview/deepLearning/cv/stable_diffusion_easyphoto
