### ISSUE TITLE
[Windows 如果缺失venv 环境需要手动安装]ModuleNotFoundError: No module named 'venv'

### ISSUE THREAD

**Issue by XiaoCC** [aigc-apps/sd-webui-EasyPhoto#33]
*** Error loading script: easyphoto_infer.py
    Traceback (most recent call last):
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 11, in <module>
        from modelscope.pipelines import pipeline
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\base.py", line 15, in <module>
        from modelscope.models.base import Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\__init__.py", line 8, in <module>
        from .base import Head, Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\__init__.py", line 4, in <module>
        from .base_head import *  # noqa F403
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_head.py", line 5, in <module>
        from modelscope.models.base.base_model import Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_model.py", line 16, in <module>
        from modelscope.utils.plugins import (register_modelhub_repo,
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\utils\plugins.py", line 12, in <module>
        import venv
    ModuleNotFoundError: No module named 'venv'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: easyphoto_train.py
    Traceback (most recent call last):
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_train.py", line 19, in <module>
        from scripts.preprocess import preprocess_images
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\preprocess.py", line 12, in <module>
        from modelscope.pipelines import pipeline
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\base.py", line 15, in <module>
        from modelscope.models.base import Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\__init__.py", line 8, in <module>
        from .base import Head, Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\__init__.py", line 4, in <module>
        from .base_head import *  # noqa F403
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_head.py", line 5, in <module>
        from modelscope.models.base.base_model import Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_model.py", line 16, in <module>
        from modelscope.utils.plugins import (register_modelhub_repo,
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\utils\plugins.py", line 12, in <module>
        import venv
    ModuleNotFoundError: No module named 'venv'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: easyphoto_ui.py
    Traceback (most recent call last):
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_ui.py", line 7, in <module>
        from scripts.easyphoto_infer import easyphoto_infer_forward
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 11, in <module>
        from modelscope.pipelines import pipeline
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\base.py", line 15, in <module>
        from modelscope.models.base import Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\__init__.py", line 8, in <module>
        from .base import Head, Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\__init__.py", line 4, in <module>
        from .base_head import *  # noqa F403
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_head.py", line 5, in <module>
        from modelscope.models.base.base_model import Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_model.py", line 16, in <module>
        from modelscope.utils.plugins import (register_modelhub_repo,
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\utils\plugins.py", line 12, in <module>
        import venv
    ModuleNotFoundError: No module named 'venv'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: preprocess.py
    Traceback (most recent call last):
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-EasyPhoto\scripts\preprocess.py", line 12, in <module>
        from modelscope.pipelines import pipeline
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\pipelines\base.py", line 15, in <module>
        from modelscope.models.base import Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\__init__.py", line 8, in <module>
        from .base import Head, Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\__init__.py", line 4, in <module>
        from .base_head import *  # noqa F403
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_head.py", line 5, in <module>
        from modelscope.models.base.base_model import Model
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\models\base\base_model.py", line 16, in <module>
        from modelscope.utils.plugins import (register_modelhub_repo,
      File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\modelscope\utils\plugins.py", line 12, in <module>
        import venv
    ModuleNotFoundError: No module named 'venv'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**### 用的秋叶整合包更新到最新的1.6版本安装插件后启动报错。**

**Comment by yunkchen** [comment]
可能是因为你的Python环境不是通过Anaconda安装的，没有自带这个包，试着在cmd命令窗口跑：
`py -m pip install virtualenv`

**Comment by wuziheng** [comment]
已解决
