### ISSUE TITLE
训练完成后无法生成

### ISSUE THREAD

**Issue by wangxshuai** [aigc-apps/sd-webui-EasyPhoto#34]
报错日志:
2023-09-07 10:11:51,501 - modelscope - WARNING - Find task: face-detection, model type: None. Insufficient information to build preprocessor, skip building preprocessor
2023-09-07 10:11:51,502 - modelscope - INFO - loading model from /root/.cache/modelscope/hub/damo/cv_resnet50_face-detection_retinaface/pytorch_model.pt
2023-09-07 10:11:52,056 - modelscope - INFO - load model done
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    session_state = {}
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    Calls function with given index and preprocessed input, and measures process time.
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/data/weiui/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 214, in easyphoto_infer_forward
    best_outputs_paths = glob.glob(os.path.join(user_id_outpath_samples, user_id, "user_weights", "best_outputs", "*.jpg"))
  File "/root/miniconda3/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/root/miniconda3/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

采用了默认的模板,设定了id,默认参数运行

**Comment by wuziheng** [comment]
@wangxshuai 
best_outputs_paths = glob.glob(os.path.join(user_id_outpath_samples, user_id, "user_weights", "best_outputs", ".jpg"))
File "/root/miniconda3/lib/python3.10/posixpath.py", line 90, in join
genericpath._check_arg_types('join', a, *p)
File "/root/miniconda3/lib/python3.10/genericpath.py", line 152, in _check_arg_types
raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'


 这句话的
 best_outputs_paths = glob.glob(os.path.join(user_id_outpath_samples, user_id, "user_weights", "best_outputs", ".jpg"))
 执行的是去找到一个最好的生成图片的id模板，但报错代表输入参数user_id_outpath_samples， user_id 有一个可能是NoneType， 如果你可以debug代码，你可以在这句话之前
 加2句
 print("user_id : ", user_id)
  print("user_id_outpath_samples : ", user_id_outpath_samples)
 判断一下哪个变量是None，以及Why。
这个bug我们自己没有遇到，但是很乐于帮你一起联调看看什么问题导致了这个bug，最新的PR里面有钉钉群可以搜索加入，方便一起联调

**Comment by wangxshuai** [comment]
> @wangxshuai best_outputs_paths = glob.glob(os.path.join(user_id_outpath_samples, user_id, "user_weights", "best_outputs", ".jpg")) File "/root/miniconda3/lib/python3.10/posixpath.py", line 90, in join genericpath._check_arg_types('join', a, *p) File "/root/miniconda3/lib/python3.10/genericpath.py", line 152, in _check_arg_types raise TypeError(f'{funcname}() argument must be str, bytes, or ' TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
> 
> 这句话的 best_outputs_paths = glob.glob(os.path.join(user_id_outpath_samples, user_id, "user_weights", "best_outputs", ".jpg")) 执行的是去找到一个最好的生成图片的id模板，但报错代表输入参数user_id_outpath_samples， user_id 有一个可能是NoneType， 如果你可以debug代码，你可以在这句话之前 加2句 print("user_id : ", user_id) print("user_id_outpath_samples : ", user_id_outpath_samples) 判断一下哪个变量是None，以及Why。 这个bug我们自己没有遇到，但是很乐于帮你一起联调看看什么问题导致了这个bug，最新的PR里面有钉钉群可以搜索加入，方便一起联调

我想加入,但没有找到你所说的群,另外你所说的调试方法,我会去尝试.

**Comment by wuziheng** [comment]
![1694055763992](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/11889926/2e1d7b19-cabc-44d7-b0d6-49cb643ca9d8)
刷新一下readme，欢迎你的加入。

**Comment by vikiiing** [comment]
报错日志:
Traceback (most recent call last):
  File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\AI\sd-webui-aki-v4.2\SD1_5\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 419, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint_with_mask_face(input_image, input_mask, replaced_input_image, diffusion_steps=first_diffusion_steps, denoising_strength=first_denoising_strength, input_prompt=input_prompts[index], hr_scale=1.0, seed=str(seed))
  File "D:\AI\sd-webui-aki-v4.2\SD1_5\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 113, in inpaint_with_mask_face
    image = i2i_inpaint_call(
  File "D:\AI\sd-webui-aki-v4.2\SD1_5\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 285, in i2i_inpaint_call
    h_1, w_1, c_1 = np.shape(processed.images[1])
IndexError: list index out of range
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by aetherwu** [comment]
> @wangxshuai best_outputs_paths = glob.glob(os.path.join(user_id_outpath_samples, user_id, "user_weights", "best_outputs", ".jpg")) File "/root/miniconda3/lib/python3.10/posixpath.py", line 90, in join genericpath._check_arg_types('join', a, *p) File "/root/miniconda3/lib/python3.10/genericpath.py", line 152, in _check_arg_types raise TypeError(f'{funcname}() argument must be str, bytes, or ' TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
> 
> 这句话的 best_outputs_paths = glob.glob(os.path.join(user_id_outpath_samples, user_id, "user_weights", "best_outputs", ".jpg")) 执行的是去找到一个最好的生成图片的id模板，但报错代表输入参数user_id_outpath_samples， user_id 有一个可能是NoneType， 如果你可以debug代码，你可以在这句话之前 加2句 print("user_id : ", user_id) print("user_id_outpath_samples : ", user_id_outpath_samples) 判断一下哪个变量是None，以及Why。 这个bug我们自己没有遇到，但是很乐于帮你一起联调看看什么问题导致了这个bug，最新的PR里面有钉钉群可以搜索加入，方便一起联调

用 telegram 或者 discord 来沟通吧！

**Comment by aetherwu** [comment]
> 报错日志: Traceback (most recent call last): File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\gradio\routes.py", line 422, in run_predict output = await app.get_blocks().process_api( File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api result = await self.call_function( File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function prediction = await anyio.to_thread.run_sync( File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread return await future File "D:\AI\sd-webui-aki-v4.2\SD1_5\python\lib\site-packages\anyio_backends_asyncio.py", line 867, in run result = context.run(func, *args) File "D:\AI\sd-webui-aki-v4.2\SD1_5\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 419, in easyphoto_infer_forward first_diffusion_output_image = inpaint_with_mask_face(input_image, input_mask, replaced_input_image, diffusion_steps=first_diffusion_steps, denoising_strength=first_denoising_strength, input_prompt=input_prompts[index], hr_scale=1.0, seed=str(seed)) File "D:\AI\sd-webui-aki-v4.2\SD1_5\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 113, in inpaint_with_mask_face image = i2i_inpaint_call( File "D:\AI\sd-webui-aki-v4.2\SD1_5\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 285, in i2i_inpaint_call h_1, w_1, c_1 = np.shape(processed.images[1]) IndexError: list index out of range 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

我遇到了一模一样的问题。

**Comment by wuziheng** [comment]
@aetherwu 这个问题可能是由于
1. 部分社区工具包修改了controlnet的输出，删除了中间变量的输出
2. controlnet 预测失败， 可能是最大数目设置问题 or 重启一下就好了
还没有遇到其他情形， 欢迎补充，然后我们已经在PR50 和最新的代码添加了容错，欢迎再尝试一下。
关于你的discord 和telegram的建议，我们会尽快更新。

**Comment by aetherwu** [comment]
> @aetherwu 这个问题可能是由于
> 
> 1. 部分社区工具包修改了controlnet的输出，删除了中间变量的输出
> 2. controlnet 预测失败， 可能是最大数目设置问题 or 重启一下就好了
>    还没有遇到其他情形， 欢迎补充，然后我们已经在PR50 和最新的代码添加了容错，欢迎再尝试一下。
>    关于你的discord 和telegram的建议，我们会尽快更新。

更新以后， 现在我这边好了。
