### ISSUE TITLE
！！！为什么训练的时候 老是到了 user-weight 这个目录的这一步的时候就训练失败了 求助大神！！！

### ISSUE THREAD

**Issue by ccIsCool6** [aigc-apps/sd-webui-EasyPhoto#348]
Dataset imagefolder downloaded and prepared to D:/AI画图/sd-webui-aki-v4.5/.cache/huggingface/datasets/imagefolder/default-cfc16c9309caaa76/0.0.0/37fbb85cc714a338bea574ac6c7d0b5be5aff46c1862c1989b20e0771199e93f. Subsequent calls will reuse this data.
Traceback (most recent call last):
  File "D:\AI画图\sd-webui-aki-v4.5\extensions\sd-webui-EasyPhoto\scripts\train_kohya\train_lora.py", line 1370, in <module>
    main()
  File "D:\AI画图\sd-webui-aki-v4.5\extensions\sd-webui-EasyPhoto\scripts\train_kohya\utils\gpu_info.py", line 195, in wrapper
    result = func(*args, **kwargs)
  File "D:\AI画图\sd-webui-aki-v4.5\extensions\sd-webui-EasyPhoto\scripts\train_kohya\train_lora.py", line 1001, in main
    accelerator.init_trackers("text2image-fine-tune", config=vars(args))
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\accelerator.py", line 602, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\accelerator.py", line 2199, in init_trackers
    tracker_init(project_name, self.logging_dir, **init_kwargs.get(str(tracker), {}))
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\tracking.py", line 84, in execute_on_main_process
    return PartialState().on_main_process(function)(self, *args, **kwargs)
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\tracking.py", line 191, in __init__
    self.writer = tensorboard.SummaryWriter(self.logging_dir, **kwargs)
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\torch\utils\tensorboard\writer.py", line 243, in __init__
    self._get_file_writer()
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\torch\utils\tensorboard\writer.py", line 273, in _get_file_writer
    self.file_writer = FileWriter(
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\torch\utils\tensorboard\writer.py", line 72, in __init__
    self.event_writer = EventFileWriter(
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 513, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.FailedPreconditionError
: outputs\easyphoto-user-id-infos\wjh lora2\user_weights is not a directory
Traceback (most recent call last):
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\commands\launch.py", line 989, in <module>
    main()
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\commands\launch.py", line 985, in main
    launch_command(args)
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\commands\launch.py", line 979, in launch_command
    simple_launcher(args)
  File "D:\AI画图\sd-webui-aki-v4.5\python\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\AI画图\\sd-webui-aki-v4.5\\python\\python.exe', 'D:\\AI画图\\sd-webui-aki-v4.5\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\realisticVisionV60B1_v60B1VAE(only pep).safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\wjh lora2\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=1000', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=277210', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=outputs\\easyphoto-user-id-infos\\wjh lora2\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\wjh lora2\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=wjh lora2', '--cache_log_file=D:\\AI画图\\sd-webui-aki-v4.5\\outputs/easyphoto-tmp/train_kohya_log.txt', '--validation']' returned non-zero exit status 1.
<img width="137" alt="微信图片_20231225185702" src="https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/151799590/6d1b56d0-58b3-47f3-8db0-8cdd89a65305">

**Comment by wuziheng** [comment]
目录不要出现中文，你的AI画图 要改成别的。
