### ISSUE TITLE
启动失败 报错 

### ISSUE THREAD

**Issue by ni94wei1** [aigc-apps/sd-webui-EasyPhoto#363]
Error loading script: sdwebui.py
    Traceback (most recent call last):
      File "D:\Game\AI\novelai-webui\novelai-webui-aki-v2\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Game\AI\novelai-webui\novelai-webui-aki-v2\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Game\AI\novelai-webui\novelai-webui-aki-v2\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 22, in <module>
        from scripts.easyphoto_utils import (
      File "D:\Game\AI\novelai-webui\novelai-webui-aki-v2\extensions\sd-webui-EasyPhoto\scripts\easyphoto_utils\__init__.py", line 32, in <module>
        from .common_utils import (
      File "D:\Game\AI\novelai-webui\novelai-webui-aki-v2\extensions\sd-webui-EasyPhoto\scripts\easyphoto_utils\common_utils.py", line 17, in <module>
        from modelscope.utils.logger import get_logger as ms_get_logger
    ModuleNotFoundError: No module named 'modelscope'

**Comment by aetherwu** [comment]
I've got 

**
\extensions\sd-webui-EasyPhoto\scripts\easyphoto_utils\tryon_utils.py", line 13, in <module>
        from shapely.geometry import Polygon
    ModuleNotFoundError: No module named 'shapely'
**

for WebUI 1.7

**Comment by wuziheng** [comment]
Try to use 
pip install modelscope
pip install shapely 

to solve
