### ISSUE TITLE
problem with photo inference[photo2photo]: EasyPhoto - Template 1 error: Error info is Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same, skip it.

### ISSUE THREAD

**Issue by ShangZhang0407** [aigc-apps/sd-webui-EasyPhoto#366]
I have trained with uploaded images, but when I use template 1 for photo-to-photo inference, the following error is reported:

Traceback (most recent call last):
  File "/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 1289, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(
  File "/software/anaconda3/envs/sd/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 372, in inpaint
    image = i2i_inpaint_call(
  File "/software/anaconda3/envs/sd/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/sdwebui.py", line 721, in i2i_inpaint_call
    processed = processing.process_images(p_img2img)
  File "/stable-diffusion-webui/modules/processing.py", line 734, in process_images
    res = process_images_inner(p)
  File "/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/stable-diffusion-webui/modules/processing.py", line 804, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/stable-diffusion-webui/modules/processing.py", line 1495, in init
    self.init_latent = images_tensor_to_samples(image, approximation_indexes.get(opts.sd_vae_encode_method), self.sd_model)
  File "/stable-diffusion-webui/modules/sd_samplers_common.py", line 110, in images_tensor_to_samples
    x_latent = model.get_first_stage_encoding(model.encode_first_stage(image))
  File "/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/software/anaconda3/envs/sd/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "/software/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/software/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/model.py", line 523, in forward
    hs = [self.conv_in(x)]
  File "/software/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/software/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 501, in network_Conv2d_forward
    return originals.Conv2d_forward(self, input)
  File "/software/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/software/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same
2024-01-09 08:55:59,973 - EasyPhoto - Template 1 error: Error info is Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same, skip it.

My running environment is Ubuntu system with 4 4090 RTX. I want to use gpu for infering, this error seems to be a conflict between gpu data and cpu data. But I don't know which network or data should be put on cuda, which part of the code should I modify to fix it?

**Comment by hkunzhe** [comment]
@ShangZhang0407, It looks like the issue was caused by the SD Web UI. Could you provide the version and launch command for the SD WebUI. From my experience, simply restart SD Web UI would fix this.

**Comment by ShangZhang0407** [comment]
> @ShangZhang0407, It looks like the issue was caused by the SD Web UI. Could you provide the version and launch command for the SD WebUI. From my experience, simply restart SD Web UI would fix this.

Thanks for your reply. I just cloned it from this project "https://github.com/AUTOMATIC1111/stable-diffusion-webui"，and its version is v1.7.0. My launch conmmand is "python webui.py --listen --enable-insecure-extension-access --port 7860 --share --xformers"
