### ISSUE TITLE
项目与roop有冲突？试了好几次，下架项目，roop就正常？

### ISSUE THREAD

**Issue by newstargo** [aigc-apps/sd-webui-EasyPhoto#38]
*** Error running postprocess_image: C:\Users\nsg\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py
    Traceback (most recent call last):
      File "C:\Users\nsg\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\nsg\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 191, in postprocess_image
        pp = scripts_postprocessing.PostprocessedImage(result.image())
      File "C:\Users\nsg\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 528, in __getattr__
        raise AttributeError(name)
    AttributeError: image

---

**Comment by bubbliiiing** [comment]
不好意思，我没有看明白问题，请问是运行roop出错还是运行Easyphoto出错？

**Comment by newstargo** [comment]
就是easyphoto插件允许生效，没运行，运行文生图启动roop，生图后roop不能换脸后，就出现上面出错信息。只要关了插件，再运行roop，能正常换脸。

**Comment by newstargo** [comment]
> 不好意思，我没有看明白问题，请问是运行roop出错还是运行Easyphoto出错？

找到原因了吗？

**Comment by newstargo** [comment]
> 不好意思，我没有看明白问题，请问是运行roop出错还是运行Easyphoto出错？

找到原因了吗？

**Comment by bubbliiiing** [comment]
已经解除insightface依赖，应该没有任何冲突。
