### ISSUE TITLE
  File "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict     output = await app.get_blocks().process_api(

### ISSUE THREAD

**Issue by dxh8286239** [aigc-apps/sd-webui-EasyPhoto#382]
2024-01-21 00:57:34,969 - EasyPhoto - Skin Retouching model load error. Error Info: SkinRetouchingTorchPipeline: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1106 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

2024-01-21 00:57:35,284 - EasyPhoto - Start templates and user_ids preprocess.
Reusing loaded model anything-v5-PrtRE.safetensors [7f96a1a9ca] to load Chilloutmix-Ni-pruned-fp16-fix.safetensors [59ffe2243a]
Loading weights [59ffe2243a] from G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\models\Stable-diffusion\Chilloutmix-Ni-pruned-fp16-fix.safetensors
Loading VAE weights specified in settings: G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\models\VAE\animevae.pt
Applying attention optimization: xformers... done.
Weights loaded in 1.2s (load weights from disk: 0.2s, apply weights to model: 0.5s, load VAE: 0.5s).
Loading VAE weights specified in settings: G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
VAE weights loaded.
Cleanup completed.
Reusing loaded model Chilloutmix-Ni-pruned-fp16-fix.safetensors [59ffe2243a] to load anything-v5-PrtRE.safetensors [7f96a1a9ca]
Loading weights [7f96a1a9ca] from G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\models\Stable-diffusion\anything-v5-PrtRE.safetensors
Loading VAE weights specified in settings: G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
Weights loaded in 1.0s (load weights from disk: 0.2s, apply weights to model: 0.5s, load VAE: 0.2s).
Loading VAE weights specified in settings: G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\models\VAE\animevae.pt
Applying attention optimization: xformers... done.
VAE weights loaded.
Traceback (most recent call last):
  File "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\python\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\python\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "G:\stable diffusion\sd-webui-aki\sd-webui-aki-v4.4\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 932, in easyphoto_infer_forward
    _face_id_retinaface_box = _face_id_retinaface_boxes[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by dxh8286239** [comment]
训练结束后，在推理时出错

**Comment by dxh8286239** [comment]
[Uploading Diagnostics-1705770287.log…]()

**Comment by wuziheng** [comment]
看起来是推理图片没有检测到人脸
