### ISSUE TITLE
modelscope.hub.errors.FileDownloadError: File CurricularFace_Backbone.pth download incomplete, content_length: 260837256 but the file downloaded length: 111607808, please download again

### ISSUE THREAD

**Issue by aswordok** [aigc-apps/sd-webui-EasyPhoto#383]
2024-01-23 15:09:52,224 - modelscope - INFO - PyTorch version 2.1.0+cu118 Found.
2024-01-23 15:09:52,230 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2024-01-23 15:09:52,230 - modelscope - INFO - Loading ast index from E:\+StableDiffusion\sd-webui-aki\.cache\modelscope\hub\ast_indexer
2024-01-23 15:09:52,320 - modelscope - INFO - Loading done! Current index file version is 1.9.3, with md5 8997bb470c5697c653bb822bc444e3a8 and a total number of 943 components indexed
2024-01-23 15:09:54,163 - modelscope - INFO - Use user-specified model revision: v1.0.3
2024-01-23 15:10:24,995 - modelscope - ERROR - File CurricularFace_Backbone.pth download incomplete, content_length: 260837256 but the                     file downloaded length: 111607808, please download again
Traceback (most recent call last):
  File "E:\+StableDiffusion\sd-webui-aki\extensions\sd-webui-EasyPhoto\scripts\preprocess.py", line 113, in <module>
    face_recognition = pipeline("face_recognition", model="bubbliiiing/cv_retinafce_recognition", model_revision="v1.0.3")
  File "E:\+StableDiffusion\sd-webui-aki\python\lib\site-packages\modelscope\pipelines\builder.py", line 117, in pipeline
    model = normalize_model_input(
  File "E:\+StableDiffusion\sd-webui-aki\python\lib\site-packages\modelscope\pipelines\builder.py", line 38, in normalize_model_input
    model = snapshot_download(
  File "E:\+StableDiffusion\sd-webui-aki\python\lib\site-packages\modelscope\hub\snapshot_download.py", line 149, in snapshot_download
    http_get_file(
  File "E:\+StableDiffusion\sd-webui-aki\python\lib\site-packages\modelscope\hub\file_download.py", line 343, in http_get_file
    raise FileDownloadError(msg)
modelscope.hub.errors.FileDownloadError: File CurricularFace_Backbone.pth download incomplete, content_length: 260837256 but the                     file downloaded length: 111607808, please download again
2024-01-23 15:10:27,958 - EasyPhoto - Error executing the command: Command '['E:\\+StableDiffusion\\sd-webui-aki\\python\\python.exe', 'E:\\+StableDiffusion\\sd-webui-aki\\extensions\\sd-webui-EasyPhoto\\scripts\\preprocess.py', '--images_save_path=E:\\+StableDiffusion\\sd-webui-aki\\outputs/easyphoto-user-id-infos\\niuy\\processed_images\\train', '--json_save_path=E:\\+StableDiffusion\\sd-webui-aki\\outputs/easyphoto-user-id-infos\\niuy\\processed_images\\metadata.jsonl', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--inputs_dir=E:\\+StableDiffusion\\sd-webui-aki\\outputs/easyphoto-user-id-infos\\niuy\\original_backup', '--ref_image_path=E:\\+StableDiffusion\\sd-webui-aki\\outputs/easyphoto-user-id-infos\\niuy\\ref_image.jpg', '--crop_ratio=3', '--skin_retouching_bool']' returned non-zero exit status 1.
2024-01-23 15:10:27,958 - EasyPhoto - Failed to obtain preprocessed images, please check the preprocessing process.
Using already loaded model maijiReal.safetensors [7c819b6d13]: done in 0.6s (send model to device: 0.6s)
Applying attention optimization: xformers... done.

**Comment by aswordok** [comment]
The problem has been solved :
Download the file from here: https://github.com/HuangYG123/CurricularFace?tab=readme-ov-file,
and put it into ...\extensions\sd-webui-EasyPhoto\models
