### ISSUE TITLE
關於 Enable RL (Reinforcement Learning) 使用上的問題

### ISSUE THREAD

**Issue by karta0655127** [aigc-apps/sd-webui-EasyPhoto#387]
請問我在到了設定的時間 "max time (hours) of RL" 後訓練停止，有辦法將RL的訓練結果在txt2img使用嗎？
一般訓練結束後可以將faceid.safetensorsk的檔案在txt2img直接以LoRA使用，但RL訓練後的成果該如何在txt2img中使用？
謝謝！第一次接觸RL類的東西還不是很清楚怎麼使用，也搜尋不到相關的教學，再麻煩協助了！

在時間到了訓練停止後會出現以下訊息

*** Error verifying pickled file from D:\mix\work\stable-diffusion-webui\outputs/easyphoto-user-id-infos\nana1127\ddpo_weights\best_outputs\pytorch_lora_weights.bin
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
***
    Traceback (most recent call last):
      File "D:\mix\work\stable-diffusion-webui\modules\safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "D:\mix\work\stable-diffusion-webui\modules\safe.py", line 83, in check_pt
        with zipfile.ZipFile(filename) as z:
      File "C:\Program Files\Python310\lib\zipfile.py", line 1249, in __init__
        self.fp = io.open(file, filemode)
    FileNotFoundError: [Errno 2] No such file or directory: 'D:\\mix\\work\\stable-diffusion-webui\\outputs/easyphoto-user-id-infos\\nana1127\\ddpo_weights\\best_outputs\\pytorch_lora_weights.bin'

---
Applying attention optimization: xformers... done.
Traceback (most recent call last):
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Program Files\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "D:\mix\work\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_train.py", line 453, in easyphoto_train_forward
    convert_lora_to_safetensors(ddpo_lora_path, ddpo_webui_save_path)
  File "D:\mix\work\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\train_kohya\utils\lora_utils.py", line 1328, in convert_lora_to_safetensors
    for idx, key in enumerate(checkpoint):
TypeError: 'NoneType' object is not iterable

**Comment by karta0655127** [comment]
嘗試在啟動選項加入 --disable-safe-unpickle 之後有機率RL可以訓練完成，但成功的機率不是很高，大多時候都會跳出下列失敗訊息，目前測試了10ˇ多次只有2次成功。

Traceback (most recent call last):
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Program Files\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "D:\mix\work\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_train.py", line 453, in easyphoto_train_forward
    convert_lora_to_safetensors(ddpo_lora_path, ddpo_webui_save_path)
  File "D:\mix\work\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\train_kohya\utils\lora_utils.py", line 1322, in convert_lora_to_safetensors
    checkpoint = torch.load(in_lora_file, map_location=torch.device("cuda"))
  File "D:\mix\work\stable-diffusion-webui\modules\safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "D:\mix\work\stable-diffusion-webui\modules\safe.py", line 156, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\mix\work\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\mix\\work\\stable-diffusion-webui\\outputs/easyphoto-user-id-infos\\mina0321\\ddpo_weights\\best_outputs\\pytorch_lora_weights.bin'

**Comment by yasainet** [comment]
Same problem 🥲

**Comment by wuziheng** [comment]
似乎有概率RL并没有完成训练，RL是额外的进程训练的输出在 ddpo_weights 中，如果可以在其中找到就可以正常移动到lora中使用。
@hkunzhe

**Comment by hkunzhe** [comment]
@karta0655127 @yasainet, Given the `user_id`, you can find the user LoRA `user_id.safetensors` and its corresponding RL LoRA `ddpo_user_id.safetensors` (if Enable RL) in `stable-diffusion/webui/models/Lora`. To use the above two LoRAs together, you can prompt with `easyphoto_face, easyphoto, 1 person <lora:user_id:1> <lora:ddpo_user_id:1>`.
