### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by zyjlqx** [aigc-apps/sd-webui-EasyPhoto#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Is EasyPhoto the latest version?

- [X] I have updated EasyPhoto to the latest version and the bug still exists.

### What happened?

2024-02-21 10:03:53,039 - EasyPhoto - train_file_path : /home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py
2024-02-21 10:03:53,039 - EasyPhoto - cache_log_file_path: /home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt
Traceback (most recent call last):
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 989, in <module>
    main()
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in main
    launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'
2024-02-21 10:03:55,101 - EasyPhoto - Error executing the command: Command '['/home/wugq/anaconda3/envs/sd/bin/python3', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', '/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py', '--pretrained_model_name_or_path=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', '--pretrained_model_ckpt=/home/zyzy/stable-diffusion-webui/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=2', '--gradient_accumulation_steps=4', '--dataloader_num_workers=16', '--max_train_steps=2000', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=161775', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--logging_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=lf', '--cache_log_file=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt']' returned non-zero exit status 1.
Using already loaded model 叮当自用v3底膜_大模型_v1.0.safetensors [e945cd457f]: done in 0.4s (send model to device: 0.4s)
Applying attention optimization: xformers... done.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
2024-02-21 10:03:53,039 - EasyPhoto - train_file_path : /home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py
2024-02-21 10:03:53,039 - EasyPhoto - cache_log_file_path: /home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt
Traceback (most recent call last):
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 989, in <module>
    main()
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in main
    launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'
2024-02-21 10:03:55,101 - EasyPhoto - Error executing the command: Command '['/home/wugq/anaconda3/envs/sd/bin/python3', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', '/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py', '--pretrained_model_name_or_path=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', '--pretrained_model_ckpt=/home/zyzy/stable-diffusion-webui/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=2', '--gradient_accumulation_steps=4', '--dataloader_num_workers=16', '--max_train_steps=2000', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=161775', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--logging_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=lf', '--cache_log_file=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt']' returned non-zero exit status 1.
Using already loaded model 叮当自用v3底膜_大模型_v1.0.safetensors [e945cd457f]: done in 0.4s (send model to device: 0.4s)
Applying attention optimization: xformers... done.

### What should have happened?

zc

### Commit where the problem happens

webui: 
EastPhoto: 
2024-02-21 10:03:53,039 - EasyPhoto - train_file_path : /home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py
2024-02-21 10:03:53,039 - EasyPhoto - cache_log_file_path: /home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt
Traceback (most recent call last):
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 989, in <module>
    main()
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in main
    launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'
2024-02-21 10:03:55,101 - EasyPhoto - Error executing the command: Command '['/home/wugq/anaconda3/envs/sd/bin/python3', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', '/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py', '--pretrained_model_name_or_path=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', '--pretrained_model_ckpt=/home/zyzy/stable-diffusion-webui/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=2', '--gradient_accumulation_steps=4', '--dataloader_num_workers=16', '--max_train_steps=2000', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=161775', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--logging_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=lf', '--cache_log_file=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt']' returned non-zero exit status 1.
Using already loaded model 叮当自用v3底膜_大模型_v1.0.safetensors [e945cd457f]: done in 0.4s (send model to device: 0.4s)
Applying attention optimization: xformers... done.

### Command Line Arguments

```Shell
2024-02-21 10:03:53,039 - EasyPhoto - train_file_path : /home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py
2024-02-21 10:03:53,039 - EasyPhoto - cache_log_file_path: /home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt
Traceback (most recent call last):
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 989, in <module>
    main()
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in main
    launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'
2024-02-21 10:03:55,101 - EasyPhoto - Error executing the command: Command '['/home/wugq/anaconda3/envs/sd/bin/python3', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', '/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py', '--pretrained_model_name_or_path=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', '--pretrained_model_ckpt=/home/zyzy/stable-diffusion-webui/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=2', '--gradient_accumulation_steps=4', '--dataloader_num_workers=16', '--max_train_steps=2000', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=161775', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--logging_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=lf', '--cache_log_file=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt']' returned non-zero exit status 1.
Using already loaded model 叮当自用v3底膜_大模型_v1.0.safetensors [e945cd457f]: done in 0.4s (send model to device: 0.4s)
Applying attention optimization: xformers... done.
```

### List of enabled extensions

2024-02-21 10:03:53,039 - EasyPhoto - train_file_path : /home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py
2024-02-21 10:03:53,039 - EasyPhoto - cache_log_file_path: /home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt
Traceback (most recent call last):
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 989, in <module>
    main()
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in main
    launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'
2024-02-21 10:03:55,101 - EasyPhoto - Error executing the command: Command '['/home/wugq/anaconda3/envs/sd/bin/python3', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', '/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py', '--pretrained_model_name_or_path=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', '--pretrained_model_ckpt=/home/zyzy/stable-diffusion-webui/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=2', '--gradient_accumulation_steps=4', '--dataloader_num_workers=16', '--max_train_steps=2000', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=161775', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--logging_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=lf', '--cache_log_file=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt']' returned non-zero exit status 1.
Using already loaded model 叮当自用v3底膜_大模型_v1.0.safetensors [e945cd457f]: done in 0.4s (send model to device: 0.4s)
Applying attention optimization: xformers... done.

### Console logs

```Shell
2024-02-21 10:03:53,039 - EasyPhoto - train_file_path : /home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py
2024-02-21 10:03:53,039 - EasyPhoto - cache_log_file_path: /home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt
Traceback (most recent call last):
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wugq/anaconda3/envs/sd/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 989, in <module>
    main()
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in main
    launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 957, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 821, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/zyzy/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'
2024-02-21 10:03:55,101 - EasyPhoto - Error executing the command: Command '['/home/wugq/anaconda3/envs/sd/bin/python3', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', '/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/train_kohya/train_lora.py', '--pretrained_model_name_or_path=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/stable-diffusion-v1-5', '--pretrained_model_ckpt=/home/zyzy/stable-diffusion-webui/models/Stable-diffusion/Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=2', '--gradient_accumulation_steps=4', '--dataloader_num_workers=16', '--max_train_steps=2000', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=161775', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=100', '--output_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--logging_dir=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-user-id-infos/lf/user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=/home/zyzy/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/models/training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=lf', '--cache_log_file=/home/zyzy/stable-diffusion-webui/outputs/easyphoto-tmp/train_kohya_log.txt']' returned non-zero exit status 1.
Using already loaded model 叮当自用v3底膜_大模型_v1.0.safetensors [e945cd457f]: done in 0.4s (send model to device: 0.4s)
Applying attention optimization: xformers... done.
```

**Comment by paradiseHIT** [comment]
https://github.com/bmaltais/kohya_ss/issues/1554#issuecomment-1805180619
