### ISSUE TITLE
 EasyPhoto - Template 1 error: Error info is expected string or bytes-like object no template found base[Bug]: 

### ISSUE THREAD

**Issue by qigaifuren** [aigc-apps/sd-webui-EasyPhoto#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Is EasyPhoto the latest version?

- [X] I have updated EasyPhoto to the latest version and the bug still exists.

### What happened?

*** Error running process: F:\stable-diffusion-webui\modules/processing_scripts\comments.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in process
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in <listcomp>
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 6, in strip_comments
        text = re.sub('(^|\n)#[^\n]*(\n|$)', '\n', text)  # while line comment
      File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object

---
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 1525, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 390, in inpaint
    image = i2i_inpaint_call(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 721, in i2i_inpaint_call
    processed = processing.process_images(p_img2img)
  File "F:\stable-diffusion-webui\modules\processing.py", line 785, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 41, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "F:\stable-diffusion-webui\modules\processing.py", line 891, in process_images_inner
    p.parse_extra_network_prompts()
  File "F:\stable-diffusion-webui\modules\processing.py", line 512, in parse_extra_network_prompts
    self.prompts, self.extra_network_data = extra_networks.parse_prompts(self.prompts)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 199, in parse_prompts
    updated_prompt, parsed_extra_data = parse_prompt(prompt)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 189, in parse_prompt
    prompt = re.sub(re_extra_net, found, prompt)
  File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2024-03-05 11:53:13,767 - EasyPhoto - Template 1 error: Error info is expected string or bytes-like object, skip it.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
*** Error running process: F:\stable-diffusion-webui\modules/processing_scripts\comments.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in process
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in <listcomp>
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 6, in strip_comments
        text = re.sub('(^|\n)#[^\n]*(\n|$)', '\n', text)  # while line comment
      File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object

---
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 1525, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 390, in inpaint
    image = i2i_inpaint_call(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 721, in i2i_inpaint_call
    processed = processing.process_images(p_img2img)
  File "F:\stable-diffusion-webui\modules\processing.py", line 785, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 41, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "F:\stable-diffusion-webui\modules\processing.py", line 891, in process_images_inner
    p.parse_extra_network_prompts()
  File "F:\stable-diffusion-webui\modules\processing.py", line 512, in parse_extra_network_prompts
    self.prompts, self.extra_network_data = extra_networks.parse_prompts(self.prompts)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 199, in parse_prompts
    updated_prompt, parsed_extra_data = parse_prompt(prompt)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 189, in parse_prompt
    prompt = re.sub(re_extra_net, found, prompt)
  File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2024-03-05 11:53:13,767 - EasyPhoto - Template 1 error: Error info is expected string or bytes-like object, skip it.

### What should have happened?

*** Error running process: F:\stable-diffusion-webui\modules/processing_scripts\comments.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in process
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in <listcomp>
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 6, in strip_comments
        text = re.sub('(^|\n)#[^\n]*(\n|$)', '\n', text)  # while line comment
      File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object

---
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 1525, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 390, in inpaint
    image = i2i_inpaint_call(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 721, in i2i_inpaint_call
    processed = processing.process_images(p_img2img)
  File "F:\stable-diffusion-webui\modules\processing.py", line 785, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 41, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "F:\stable-diffusion-webui\modules\processing.py", line 891, in process_images_inner
    p.parse_extra_network_prompts()
  File "F:\stable-diffusion-webui\modules\processing.py", line 512, in parse_extra_network_prompts
    self.prompts, self.extra_network_data = extra_networks.parse_prompts(self.prompts)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 199, in parse_prompts
    updated_prompt, parsed_extra_data = parse_prompt(prompt)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 189, in parse_prompt
    prompt = re.sub(re_extra_net, found, prompt)
  File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2024-03-05 11:53:13,767 - EasyPhoto - Template 1 error: Error info is expected string or bytes-like object, skip it.

### Commit where the problem happens

webui: 
EastPhoto: 
*** Error running process: F:\stable-diffusion-webui\modules/processing_scripts\comments.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in process
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in <listcomp>
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 6, in strip_comments
        text = re.sub('(^|\n)#[^\n]*(\n|$)', '\n', text)  # while line comment
      File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object

---
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 1525, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 390, in inpaint
    image = i2i_inpaint_call(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 721, in i2i_inpaint_call
    processed = processing.process_images(p_img2img)
  File "F:\stable-diffusion-webui\modules\processing.py", line 785, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 41, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "F:\stable-diffusion-webui\modules\processing.py", line 891, in process_images_inner
    p.parse_extra_network_prompts()
  File "F:\stable-diffusion-webui\modules\processing.py", line 512, in parse_extra_network_prompts
    self.prompts, self.extra_network_data = extra_networks.parse_prompts(self.prompts)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 199, in parse_prompts
    updated_prompt, parsed_extra_data = parse_prompt(prompt)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 189, in parse_prompt
    prompt = re.sub(re_extra_net, found, prompt)
  File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2024-03-05 11:53:13,767 - EasyPhoto - Template 1 error: Error info is expected string or bytes-like object, skip it.

### Command Line Arguments

```Shell
*** Error running process: F:\stable-diffusion-webui\modules/processing_scripts\comments.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in process
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in <listcomp>
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 6, in strip_comments
        text = re.sub('(^|\n)#[^\n]*(\n|$)', '\n', text)  # while line comment
      File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object

---
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 1525, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 390, in inpaint
    image = i2i_inpaint_call(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 721, in i2i_inpaint_call
    processed = processing.process_images(p_img2img)
  File "F:\stable-diffusion-webui\modules\processing.py", line 785, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 41, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "F:\stable-diffusion-webui\modules\processing.py", line 891, in process_images_inner
    p.parse_extra_network_prompts()
  File "F:\stable-diffusion-webui\modules\processing.py", line 512, in parse_extra_network_prompts
    self.prompts, self.extra_network_data = extra_networks.parse_prompts(self.prompts)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 199, in parse_prompts
    updated_prompt, parsed_extra_data = parse_prompt(prompt)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 189, in parse_prompt
    prompt = re.sub(re_extra_net, found, prompt)
  File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2024-03-05 11:53:13,767 - EasyPhoto - Template 1 error: Error info is expected string or bytes-like object, skip it.
```

### List of enabled extensions

*** Error running process: F:\stable-diffusion-webui\modules/processing_scripts\comments.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in process
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in <listcomp>
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 6, in strip_comments
        text = re.sub('(^|\n)#[^\n]*(\n|$)', '\n', text)  # while line comment
      File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object

---
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 1525, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 390, in inpaint
    image = i2i_inpaint_call(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 721, in i2i_inpaint_call
    processed = processing.process_images(p_img2img)
  File "F:\stable-diffusion-webui\modules\processing.py", line 785, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 41, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "F:\stable-diffusion-webui\modules\processing.py", line 891, in process_images_inner
    p.parse_extra_network_prompts()
  File "F:\stable-diffusion-webui\modules\processing.py", line 512, in parse_extra_network_prompts
    self.prompts, self.extra_network_data = extra_networks.parse_prompts(self.prompts)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 199, in parse_prompts
    updated_prompt, parsed_extra_data = parse_prompt(prompt)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 189, in parse_prompt
    prompt = re.sub(re_extra_net, found, prompt)
  File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2024-03-05 11:53:13,767 - EasyPhoto - Template 1 error: Error info is expected string or bytes-like object, skip it.

### Console logs

```Shell
*** Error running process: F:\stable-diffusion-webui\modules/processing_scripts\comments.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in process
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 23, in <listcomp>
        p.all_prompts = [strip_comments(x) for x in p.all_prompts]
      File "F:\stable-diffusion-webui\modules/processing_scripts\comments.py", line 6, in strip_comments
        text = re.sub('(^|\n)#[^\n]*(\n|$)', '\n', text)  # while line comment
      File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object

---
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 1525, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 390, in inpaint
    image = i2i_inpaint_call(
  File "E:\anaconda3\envs\sdweb\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 721, in i2i_inpaint_call
    processed = processing.process_images(p_img2img)
  File "F:\stable-diffusion-webui\modules\processing.py", line 785, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 41, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "F:\stable-diffusion-webui\modules\processing.py", line 891, in process_images_inner
    p.parse_extra_network_prompts()
  File "F:\stable-diffusion-webui\modules\processing.py", line 512, in parse_extra_network_prompts
    self.prompts, self.extra_network_data = extra_networks.parse_prompts(self.prompts)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 199, in parse_prompts
    updated_prompt, parsed_extra_data = parse_prompt(prompt)
  File "F:\stable-diffusion-webui\modules\extra_networks.py", line 189, in parse_prompt
    prompt = re.sub(re_extra_net, found, prompt)
  File "E:\anaconda3\envs\sdweb\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2024-03-05 11:53:13,767 - EasyPhoto - Template 1 error: Error info is expected string or bytes-like object, skip it.
```

**Comment by hjj-lmx** [comment]
Have you solved it?

**Comment by qigaifuren** [comment]
yes发自我的 iPhone在 2024年3月13日，17:11，hjj-lmx ***@***.***> 写道：﻿
Have you solved it?
