### ISSUE TITLE
[Bug]: TypeError: '<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by lhldolike** [aigc-apps/sd-webui-EasyPhoto#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Is EasyPhoto the latest version?

- [X] I have updated EasyPhoto to the latest version and the bug still exists.

### What happened?

2024-03-17 22:22:46,656 - EasyPhoto - Start First diffusion.
Traceback (most recent call last):
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 1518, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 388, in inpaint
    image = i2i_inpaint_call(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 672, in i2i_inpaint_call
    p_img2img.script_args = init_default_script_args(p_img2img.scripts)
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 245, in init_default_script_args
    if last_arg_index < script.args_to:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
2024-03-17 22:22:46,713 - EasyPhoto - Template 1 error: Error info is '<' not supported between instances of 'int' and 'NoneType', skip it.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

TypeError: '<' not supported between instances of 'int' and 'NoneType'

### Commit where the problem happens

webui: 
EastPhoto: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
webui-user .bat
```

### List of enabled extensions

"G:\ai\stable-diffusion-webui\extensions\model-keyword"
"G:\ai\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111"
"G:\ai\stable-diffusion-webui\extensions\OneButtonPrompt"
"G:\ai\stable-diffusion-webui\extensions\openpose-editor"
"G:\ai\stable-diffusion-webui\extensions\SadTalker"
"G:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension"
"G:\ai\stable-diffusion-webui\extensions\SD-CN-Animation"
"G:\ai\stable-diffusion-webui\extensions\sd-dynamic-prompts"
"G:\ai\stable-diffusion-webui\extensions\sd-dynamic-thresholding"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-animatediff"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-comfyui"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-facefusion"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-faceswaplab"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-inpaint-anything"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-kohya-hiresfix"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-lcm"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-llul"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-lobe-theme"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-lora-block-weight"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-oldsix-prompt"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-openpose-editor"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-reactor"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-regional-prompter"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-roop"
"G:\ai\stable-diffusion-webui\extensions\sd-webui-segment-anything"
"G:\ai\stable-diffusion-webui\extensions\stable-diffusion-webui-depthmap-script"
"G:\ai\stable-diffusion-webui\extensions\stable-diffusion-webui-localization-zh_CN"
"G:\ai\stable-diffusion-webui\extensions\stable-diffusion-webui-rembg"
"G:\ai\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111"
"G:\ai\stable-diffusion-webui\extensions\put extensions here.txt"
"G:\ai\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete"
"G:\ai\stable-diffusion-webui\extensions\adetailer"
"G:\ai\stable-diffusion-webui\extensions\batch-face-swap"
"G:\ai\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui"
"G:\ai\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui"

### Console logs

```Shell
2024-03-17 22:22:46,656 - EasyPhoto - Start First diffusion.
Traceback (most recent call last):
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 1518, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 388, in inpaint
    image = i2i_inpaint_call(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 672, in i2i_inpaint_call
    p_img2img.script_args = init_default_script_args(p_img2img.scripts)
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 245, in init_default_script_args
    if last_arg_index < script.args_to:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

**Comment by lhldolike** [comment]
Applying attention optimization: Doggettx... done.
Weights loaded in 1.1s (load weights from disk: 0.2s, apply weights to model: 0.4s, move model to device: 0.6s).
Loading VAE weights specified in settings: G:\ai\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: Doggettx... done.
VAE weights loaded.
2024-03-17 22:22:42,833 - EasyPhoto -
            Start Generate template                 : 1;
            user_ids                                : ('2', 'none', 'none', 'none', 'none');
            sd_model_checkpoint                     : Chilloutmix-Ni-pruned-fp16-fix.safetensors;
            input_prompts                           : ['easyphoto_face, easyphoto, 1person, <lora:2:0.9>, <lora:FilmVelvia3:0.65>, masterpiece, beauty', 'none', 'none', 'none', 'none'];
            before_face_fusion_ratio                : 0.6;
            after_face_fusion_ratio                 : 0.6;
            first_diffusion_steps                   : 50;
            first_denoising_strength                : 0.45;
            second_diffusion_steps                  : 20;
            second_denoising_strength               : 0.3;
            seed                                    : 32715
            crop_face_preprocess                    : True
            apply_face_fusion_before                : True
            apply_face_fusion_after                 : True
            color_shift_middle                      : True
            color_shift_last                        : True
            super_resolution                        : True
            super_resolution_method                 : gpen
            display_score                           : True
            background_restore                      : False
            background_restore_denoising_strength   : 0.35
            makeup_transfer                         : False
            makeup_transfer_ratio                   : 0.5
            skin_retouching_bool                    : False
            face_shape_match                        : False
            id_control                              : True
            id_control_method                       : IP-Adapter Face
            ipa_weight                              : 0.3
            instantid_id_weight                     : 0.5
            instantid_ipa_weight                    : 0.5
            instantid_image_path                    : None
            ipa_image_path                          : None
            ref_mode_choose                         : Infer with User Lora
            no_user_lora_mode                       : IP-Adapter Face
            ipa_only_weight                         : 0.6
            ipa_only_image_path                     : None
            instantid_only_id_weight                : 0.5
            instantid_only_ipa_weight               : 0.5
            instantid_only_image_path               : None

2024-03-17 22:22:43,268 - EasyPhoto - Start Image resize to 512.0.
2024-03-17 22:22:43,286 - EasyPhoto - Start face detect.
2024-03-17 22:22:46,656 - EasyPhoto - Start First diffusion.
Traceback (most recent call last):
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 1518, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 388, in inpaint
    image = i2i_inpaint_call(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 672, in i2i_inpaint_call
    p_img2img.script_args = init_default_script_args(p_img2img.scripts)
  File "G:\ai\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 245, in init_default_script_args
    if last_arg_index < script.args_to:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
2024-03-17 22:22:46,713 - EasyPhoto - Template 1 error: Error info is '<' not supported between instances of 'int' and 'NoneType', skip it.
Cleanup completed.
