### ISSUE TITLE
[Bug]: 我的训练无法保存，non-zero错误

### ISSUE THREAD

**Issue by DreamPuNi** [aigc-apps/sd-webui-EasyPhoto#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Is EasyPhoto the latest version?

- [X] I have updated EasyPhoto to the latest version and the bug still exists.

### What happened?

我试着取消了验证，并且下载的也是最新版本的easy photo，但是还是没有作用，我用的是秋叶的整合包，系统是Windows11，显卡是tesla P4
[新建 文本文档.txt](https://github.com/aigc-apps/sd-webui-EasyPhoto/files/14647031/default.txt)
这是所有的日志

### Steps to reproduce the problem

1. 打开webui并打开easyphoto界面
2. 上传图片
3. 取消掉验证和肤色训练，然后输入名字开始训练

### What should have happened?

正常情况下应该保存模型，然后在推理界面使用

### Commit where the problem happens

webui: 
EastPhoto: https://github.com/aigc-apps/sd-webui-EasyPhoto

### Command Line Arguments

```Shell
否
```

### List of enabled extensions

仅仅使用了easy photo

### Console logs

```Shell
user-id-infos\asdasd\original_backup\0.jpg total scores:  0.1425384484026338 face angles 0.297806880952176
jpg: 1.jpg face_id_scores 0.38788002271409616
jpg: 4.jpg face_id_scores 0.49601703741228775
jpg: 2.jpg face_id_scores 0.5061530153211714
jpg: 3.jpg face_id_scores 0.4563659833749236
jpg: 0.jpg face_id_scores 0.1425384484026338
D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\torch\nn\functional.py:3769: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
save processed image to D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\outputs/easyphoto-user-id-infos\asdasd\processed_images\train\0.jpg
save processed image to D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\outputs/easyphoto-user-id-infos\asdasd\processed_images\train\1.jpg
save processed image to D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\outputs/easyphoto-user-id-infos\asdasd\processed_images\train\2.jpg
save processed image to D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\outputs/easyphoto-user-id-infos\asdasd\processed_images\train\3.jpg
save processed image to D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\outputs/easyphoto-user-id-infos\asdasd\processed_images\train\4.jpg
2024-03-19 15:21:44,101 - EasyPhoto - train_file_path : D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-EasyPhoto\scripts\train_kohya/train_lora.py
2024-03-19 15:21:44,101 - EasyPhoto - cache_log_file_path: D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\outputs/easyphoto-tmp/train_kohya_log.txt
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2024-03-19 15:22:08,807 - modelscope - INFO - PyTorch version 2.1.2+cu118 Found.
2024-03-19 15:22:08,811 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2024-03-19 15:22:08,812 - modelscope - INFO - Loading ast index from D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\.cache\modelscope\hub\ast_indexer
2024-03-19 15:22:08,968 - modelscope - INFO - Loading done! Current index file version is 1.9.3, with md5 ec63191a7c57d6c883a0cf6868d5bc09 and a total number of 943 components indexed
03/19/2024 15:22:10 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

{'clip_sample_range', 'dynamic_thresholding_ratio', 'sample_max_value', 'variance_type', 'timestep_spacing', 'thresholding', 'prediction_type'} was not found in config. Values will be initialized to default values.
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Traceback (most recent call last):
  File "D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\accelerate\commands\launch.py", line 989, in <module>
    main()
  File "D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\accelerate\commands\launch.py", line 985, in main
    launch_command(args)
  File "D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\accelerate\commands\launch.py", line 979, in launch_command
    simple_launcher(args)
  File "D:\ai\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\ai\\sd-webui-aki\\sd-webui-aki-v4.6.1\\sd-webui-aki-v4.6.1\\python\\python.exe', 'D:\\ai\\sd-webui-aki\\sd-webui-aki-v4.6.1\\sd-webui-aki-v4.6.1\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\asdasd\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=50', '--checkpointing_steps=50', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=977386', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=50', '--output_dir=outputs\\easyphoto-user-id-infos\\asdasd\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\asdasd\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=asdasd', '--cache_log_file=D:\\ai\\sd-webui-aki\\sd-webui-aki-v4.6.1\\sd-webui-aki-v4.6.1\\outputs/easyphoto-tmp/train_kohya_log.txt']' returned non-zero exit status 3221225477.
2024-03-19 15:23:42,748 - EasyPhoto - Error executing the command: Command '['D:\\ai\\sd-webui-aki\\sd-webui-aki-v4.6.1\\sd-webui-aki-v4.6.1\\python\\python.exe', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', 'D:\\ai\\sd-webui-aki\\sd-webui-aki-v4.6.1\\sd-webui-aki-v4.6.1\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\Chilloutmix-Ni-pruned-fp16-fix.safetensors', '--train_data_dir=outputs\\easyphoto-user-id-infos\\asdasd\\processed_images', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=50', '--checkpointing_steps=50', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=977386', '--rank=128', '--network_alpha=64', '--validation_prompt=easyphoto_face, easyphoto, 1person', '--validation_steps=50', '--output_dir=outputs\\easyphoto-user-id-infos\\asdasd\\user_weights', '--logging_dir=outputs\\easyphoto-user-id-infos\\asdasd\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=asdasd', '--cache_log_file=D:\\ai\\sd-webui-aki\\sd-webui-aki-v4.6.1\\sd-webui-aki-v4.6.1\\outputs/easyphoto-tmp/train_kohya_log.txt']' returned non-zero exit status 1.
Applying attention optimization: xformers... done.
```

**Comment by DreamPuNi** [comment]
内存太小了，望周知
