### ISSUE TITLE
_face_id_retinaface_box = _face_id_retinaface_boxes[0] IndexError: index 0 is out of bounds for axis 0 with size 0  如何解决

### ISSUE THREAD

**Issue by hqh1005** [aigc-apps/sd-webui-EasyPhoto#420]
2024-03-23 14:39:20,551 - EasyPhoto - Please choose a user id.
Cleanup completed.
Loading weights [15012c538f] from E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\models\Stable-diffusion\realisticVisionV60B1_v51VAE.safetensors
2024-03-23 14:40:24,550 - EasyPhoto - ControlNet unit number: 4
2024-03-23 14:40:24,550 - EasyPhoto - Found 1 user id(s), but only 0 image prompt(s) for IP-Adapter Control. Use the reference image corresponding to the user instead.
2024-03-23 14:40:24,550 - EasyPhoto - Display score is forced to be true when IP-Adapter Control is enabled.
Loading ResNet ArcFace
2024-03-23 14:41:10,668 - EasyPhoto - Start templates and user_ids preprocess.
Loading VAE weights specified in settings: E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
VAE weights loaded.
Cleanup completed.
Loading VAE weights specified in settings: E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\models\VAE\animevae.pt
Applying attention optimization: xformers... done.
VAE weights loaded.
Traceback (most recent call last):
  File "E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\sd\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 1164, in easyphoto_infer_forward
    _face_id_retinaface_box = _face_id_retinaface_boxes[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by wuziheng** [comment]
一般是没有检测到人脸，确认输入照片存在人脸。

**Comment by 995kill** [comment]
I also have this problem, how can this problem be solved?
