### ISSUE TITLE
[Bug]EasyPhoto 安装了最新版本，在webui中没有出现此插件

### ISSUE THREAD

**Issue by fanger7823** [aigc-apps/sd-webui-EasyPhoto#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Is EasyPhoto the latest version?

- [X] I have updated EasyPhoto to the latest version and the bug still exists.

### What happened?

我的是MAC Studio M2的CPU，是不支持M2吗？

### Steps to reproduce the problem

插件无法显示

### What should have happened?

报错

### Commit where the problem happens

 webui界面无显示不能使用

### Command Line Arguments

```Shell
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/Users/casa/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/casa/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/api.py", line 11, in <module>
        from scripts.easyphoto_infer import easyphoto_infer_forward, easyphoto_video_infer_forward
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 11, in <module>
        from modelscope.outputs import OutputKeys
    ModuleNotFoundError: No module named 'modelscope'

---
*** Error loading script: easyphoto_infer.py
    Traceback (most recent call last):
      File "/Users/casa/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/casa/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 11, in <module>
        from modelscope.outputs import OutputKeys
    ModuleNotFoundError: No module named 'modelscope'

---
*** Error loading script: easyphoto_train.py
    Traceback (most recent call last):
      File "/Users/casa/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/casa/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_train.py", line 21, in <module>
        from scripts.easyphoto_utils import check_files_exists_and_download, check_id_valid, check_scene_valid, ep_logger, unload_models
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_utils/__init__.py", line 32, in <module>
        from .common_utils import (
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_utils/common_utils.py", line 17, in <module>
        from modelscope.utils.logger import get_logger as ms_get_logger
    ModuleNotFoundError: No module named 'modelscope'

---
*** Error loading script: easyphoto_tryon_infer.py
    Traceback (most recent call last):
      File "/Users/casa/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/casa/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_tryon_infer.py", line 16, in <module>
        from segment_anything import SamPredictor, sam_model_registry
    ModuleNotFoundError: No module named 'segment_anything'

---
*** Error loading script: easyphoto_ui.py
    Traceback (most recent call last):
      File "/Users/casa/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/casa/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_ui.py", line 22, in <module>
        from scripts.easyphoto_infer import easyphoto_infer_forward, easyphoto_video_infer_forward
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 11, in <module>
        from modelscope.outputs import OutputKeys
    ModuleNotFoundError: No module named 'modelscope'

---
*** Error loading script: preprocess.py
    Traceback (most recent call last):
      File "/Users/casa/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/casa/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/preprocess.py", line 17, in <module>
        from modelscope.outputs import OutputKeys
    ModuleNotFoundError: No module named 'modelscope'

---
*** Error loading script: sdwebui.py
    Traceback (most recent call last):
      File "/Users/casa/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/casa/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/sdwebui.py", line 22, in <module>
        from scripts.easyphoto_utils import (
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_utils/__init__.py", line 32, in <module>
        from .common_utils import (
      File "/Users/casa/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_utils/common_utils.py", line 17, in <module>
        from modelscope.utils.logger import get_logger as ms_get_logger
    ModuleNotFoundError: No module named 'modelscope'
```

### List of enabled extensions

无 

### Console logs

```Shell
.
```

### Additional information

.

**Comment by mohand505** [comment]
MAC M1 It's also the same mistake

**Comment by dhammavipassi** [comment]
I have the same issue.

**Comment by dhammavipassi** [comment]
Provide the error message displayed in the terminal to claude3 and ask him to give a detailed solution. He has successfully helped me solve this problem. You can try it.

**Comment by RockyFong** [comment]
I have the same issue on my MBA M1. I also have the error message of 
"ModuleNotFoundError: No module named 'modelscope'"

I installed the module with "pip install modelscope", however it didn't solve the issue.

**Comment by dhammavipassi** [comment]
Send the error presented in the terminal to Gpt or claude, let ai analyze the cause of the error and ask him to give you a detailed solution.

**Comment by gaoyangyiqiao** [comment]
请问你是如何安装tensorflow-cpu的，我这里无法安装tensorflow-cpu，导致EasyPhoto无法安装

**Comment by hpan** [comment]
> 请问你是如何安装tensorflow-cpu的，我这里无法安装tensorflow-cpu，导致EasyPhoto无法安装

找到 install.py，将其中的 tensorflow-cpu 改为 tensorflow
