### ISSUE TITLE
[question] module(None) not found in supported modules. (type=value_error).Virtual Try On  Use error.虚拟换衣使用出错

### ISSUE THREAD

**Issue by zzz12345zzz** [aigc-apps/sd-webui-EasyPhoto#428]
Virtual Try On  Use error.虚拟换衣使用出错

<img width="1441" alt="sp240609_181731" src="https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/102435569/f2bf3a56-a3cd-442f-a1e6-8e0b2b97f38e">
<img width="888" alt="sp240609_182941" src="https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/102435569/e47ca01e-de5f-452c-b91c-27360591205f">

> Loading VAE weights specified in settings: F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
VAE weights loaded.
Loading weights [eed0bdfc49] from F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\models\Stable-diffusion\epicPhotonism_v10.safetensors
2024-06-09 18:20:23,870 - EasyPhoto - user_ids: ['demo_black_200', 'demo_black_200_mask', 'demo_dress_200', 'demo_dress_200_mask', 'demo_purple_200', 'demo_purple_200_mask', 'demo_short_200', 'demo_short_200_mask', 'demo_white_200', 'demo_white_200_mask', 'TT_200']
2024-06-09 18:20:23,870 - EasyPhoto - cloth user id: demo_black_200
2024-06-09 18:20:23,871 - EasyPhoto - LoRA of user id: demo_black_200 exists. Start Infer.
2024-06-09 18:20:23,871 - EasyPhoto - input_prompt: easyphoto, 1thing, <lora:demo_black_200:0.8>masterpiece, beauty
2024-06-09 18:20:23,933 - EasyPhoto - Start optimize angle and ratio!
2024-06-09 18:20:23,938 - EasyPhoto - target rotation: 1 to 0: 0, 2 to 0: -0.0, final_rotate: -0.0
Iteration limit reached    (Exit mode 9)
            Current function value: -0.7413598780662288
            Iterations: 100
            Function evaluations: 1091
            Gradient evaluations: 97
2024-06-09 18:20:24,476 - EasyPhoto - Set angle:0.2259074870789645, ratio: 1.1850609915140937, azimuth: 0
Merge img1, img2! Mask IoU: 0.6897414635590962
align_and_overlay_images time: 0.037000179290771484 s
2024-06-09 18:20:24,542 - EasyPhoto - Start First diffusion.
Cleanup completed.
Restoring base VAE
Applying attention optimization: xformers... done.
VAE weights loaded.
Traceback (most recent call last):
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\extensions\sd-webui-EasyPhoto\scripts\easyphoto_tryon_infer.py", line 496, in easyphoto_tryon_infer_forward
    result_img = inpaint(
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 388, in inpaint
    image = i2i_inpaint_call(
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 602, in i2i_inpaint_call
    controlnet_units = [external_code.ControlNetUnit(**controlnet_unit) for controlnet_unit in controlnet_units]
  File "F:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 602, in <listcomp>
    controlnet_units = [external_code.ControlNetUnit(**controlnet_unit) for controlnet_unit in controlnet_units]
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ControlNetUnit
module
  module(None) not found in supported modules. (type=value_error)

**Comment by hkunzhe** [comment]
cc @zouxinyi0625

**Comment by yankai-victor** [comment]
Same problem to me. Here is my controlnet version :
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | 8bbbd0e5
-- | -- | -- | --

**Comment by wolfhaohao** [comment]
大哥，解决了吗？我也是这个情况。

**Comment by yankai-victor** [comment]
update the latest version. It's ok for me.

**Comment by wolfhaohao** [comment]
谢谢，已经解决。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yankai-victor ***@***.***&gt;
发送时间: 2024年7月18日 19:44
收件人: aigc-apps/sd-webui-EasyPhoto ***@***.***&gt;
抄送: wolfhaohao ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [aigc-apps/sd-webui-EasyPhoto] [question] module(None) not found in supported modules. (type=value_error).Virtual Try On  Use error.虚拟换衣使用出错 (Issue #428)
