### ISSUE TITLE
[部分人脸模型报错需要先查验训练图片是否明显包含单张人脸]训练完，报错

### ISSUE THREAD

**Issue by sunhui0608** [aigc-apps/sd-webui-EasyPhoto#43]
jpg: 7.jpg face_id_scores 0.6320564312897047
jpg: 19.jpg face_id_scores 0.5878771045231846
jpg: 14.jpg face_id_scores 0.1949093026624526
jpg: 5.jpg face_id_scores 0.5932805170146064
jpg: 18.jpg face_id_scores 0.5313497371334172
jpg: 17.jpg face_id_scores 0.5227915373389229
jpg: 8.jpg face_id_scores 0.5211492366305912
jpg: 15.jpg face_id_scores 0.5717502106011998
jpg: 6.jpg face_id_scores 0.5081543266131069
jpg: 12.jpg face_id_scores 0.16740420898392058
jpg: 10.jpg face_id_scores 0.4865440232408242
jpg: 11.jpg face_id_scores 0.012049722207594385
jpg: 9.jpg face_id_scores 0.5337397954804464
jpg: 13.jpg face_id_scores 0.1811154251123568
jpg: 16.jpg face_id_scores 0.473920905871453
0it [00:00, ?it/s]2023-09-08 11:32:55,260 - modelscope - WARNING - task skin-retouching-torch input definition is missing
2023-09-08 11:32:57,398 - modelscope - WARNING - task skin-retouching-torch output keys are missing
12it [00:34,  2.86s/it]
Exception in thread Thread-63 (preprocess_images):
Traceback (most recent call last):
  File "C:\Users\sunhu\anaconda3\envs\sdwebui\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\sunhu\anaconda3\envs\sdwebui\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\sunhu\aigc\stable-diffusion-webui\extensions\EasyPhoto-sd-webui\scripts\preprocess.py", line 149, in preprocess_images
    sub_box     = sub_boxes[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

不清楚哪里出现的问题。

**Comment by wuziheng** [comment]
似乎是某张图片没有检测到人脸导致的，可以检查一下训练图片。

**Comment by sunhui0608** [comment]
好的，我试试

**Comment by sunhui0608** [comment]
就放了一张图片，这关过去了，不过好像后续又来个个错误  SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
<img width="850" alt="image" src="https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/7566367/83b50ada-295a-4f14-a704-a146179aa128">

**Comment by wuziheng** [comment]
欢迎进群讨论，
1. 然后你现在遇到的问题是模型加载的问题，我们确实没有遇到过。
2. 这个群友这几天也没有反馈过类似的问题，可能要麻烦你提供更多信息方便我们进一步排查

**Comment by aetherwu** [comment]
> 欢迎进群讨论，
> 
> 1. 然后你现在遇到的问题是模型加载的问题，我们确实没有遇到过。
> 2. 这个群友这几天也没有反馈过类似的问题，可能要麻烦你提供更多信息方便我们进一步排查

在这里讨论是最好的。

**Comment by spelistken** [comment]
Weights loaded in 8.4s (load weights from disk: 7.6s, apply weights to model: 0.2s, move model to device: 0.6s).
2023-12-01 08:10:54,276 - modelscope - WARNING - task skin-retouching-torch output keys are missing
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\0.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\1.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\2.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\3.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\4.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\5.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\6.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\7.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\8.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\9.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\10.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\11.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\12.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\13.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\14.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\15.jpg
save processed image to F:\baidupan\sd-webui启动器\outputs/easyphoto-scene-id-infos\lu1201\processed_images\train\16.jpg
train_file_path :  F:\baidupan\sd-webui启动器\extensions\sd-webui-EasyPhoto\scripts\train_kohya/train_lora.py
cache_log_file_path: F:\baidupan\sd-webui启动器\outputs/easyphoto-tmp/train_kohya_log.txt
2023-12-01 08:14:20.359193: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From F:\baidupan\sd-webui启动器\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2023-12-01 08:14:24.470928: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From F:\baidupan\sd-webui启动器\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2023-12-01 08:14:26,991 - modelscope - INFO - PyTorch version 2.1.0+cu121 Found.
2023-12-01 08:14:26,993 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2023-12-01 08:14:26,993 - modelscope - INFO - Loading ast index from F:\baidupan\sd-webui启动器\.cache\modelscope\hub\ast_indexer
2023-12-01 08:14:27,060 - modelscope - INFO - Loading done! Current index file version is 1.9.3, with md5 63b80fc421aa1339f6cbfb5eb8d27799 and a total number of 943 components indexed
12/01/2023 08:14:27 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

{'clip_sample_range', 'sample_max_value', 'dynamic_thresholding_ratio', 'variance_type', 'thresholding', 'prediction_type', 'timestep_spacing'} was not found in config. Values will be initialized to default values.
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
create LoRA network. base dim (rank): 256, alpha: 128
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
Downloading and preparing dataset imagefolder/default to F:/baidupan/sd-webui启动器/.cache/huggingface/datasets/imagefolder/default-79a4552ff7e08f2b/0.0.0/37fbb85cc714a338bea574ac6c7d0b5be5aff46c1862c1989b20e0771199e93f...
Dataset imagefolder downloaded and prepared to F:/baidupan/sd-webui启动器/.cache/huggingface/datasets/imagefolder/default-79a4552ff7e08f2b/0.0.0/37fbb85cc714a338bea574ac6c7d0b5be5aff46c1862c1989b20e0771199e93f. Subsequent calls will reuse this data.
Traceback (most recent call last):
  File "F:\baidupan\sd-webui启动器\extensions\sd-webui-EasyPhoto\scripts\train_kohya\train_lora.py", line 1478, in <module>
    main()
  File "F:\baidupan\sd-webui启动器\extensions\sd-webui-EasyPhoto\scripts\train_kohya\utils\gpu_info.py", line 195, in wrapper
    result = func(*args, **kwargs)
  File "F:\baidupan\sd-webui启动器\extensions\sd-webui-EasyPhoto\scripts\train_kohya\train_lora.py", line 1109, in main
    accelerator.init_trackers("text2image-fine-tune", config=vars(args))
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\accelerate\accelerator.py", line 602, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\accelerate\accelerator.py", line 2199, in init_trackers
    tracker_init(project_name, self.logging_dir, **init_kwargs.get(str(tracker), {}))
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\accelerate\tracking.py", line 84, in execute_on_main_process
    return PartialState().on_main_process(function)(self, *args, **kwargs)
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\accelerate\tracking.py", line 191, in __init__
    self.writer = tensorboard.SummaryWriter(self.logging_dir, **kwargs)
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 243, in __init__
    self._get_file_writer()
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 273, in _get_file_writer
    self.file_writer = FileWriter(
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 72, in __init__
    self.event_writer = EventFileWriter(
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 513, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.FailedPreconditionError: outputs\easyphoto-scene-id-infos\lu1201\user_weights is not a directory
Traceback (most recent call last):
  File "C:\Users\speli\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\speli\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\accelerate\commands\launch.py", line 989, in <module>
    main()
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\accelerate\commands\launch.py", line 985, in main
    launch_command(args)
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\accelerate\commands\launch.py", line 979, in launch_command
    simple_launcher(args)
  File "F:\baidupan\sd-webui启动器\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\baidupan\\sd-webui启动器\\venv\\Scripts\\Python.exe', 'F:\\baidupan\\sd-webui启动器\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\lofi_v4.safetensors', '--train_data_dir=outputs\\easyphoto-scene-id-infos\\lu1201\\processed_images', '--caption_column=text', '--resolution=768', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=256', '--network_alpha=128', '--validation_prompt=, special_scene, scene', '--validation_steps=100', '--output_dir=outputs\\easyphoto-scene-id-infos\\lu1201\\user_weights', '--logging_dir=outputs\\easyphoto-scene-id-infos\\lu1201\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=lu1201', '--cache_log_file=F:\\baidupan\\sd-webui启动器\\outputs/easyphoto-tmp/train_kohya_log.txt', '--train_scene_lora_bool']' returned non-zero exit status 1.
Error executing the command: Command '['F:\\baidupan\\sd-webui启动器\\venv\\Scripts\\Python.exe', '-m', 'accelerate.commands.launch', '--mixed_precision=fp16', '--main_process_port=3456', 'F:\\baidupan\\sd-webui启动器\\extensions\\sd-webui-EasyPhoto\\scripts\\train_kohya/train_lora.py', '--pretrained_model_name_or_path=extensions\\sd-webui-EasyPhoto\\models\\stable-diffusion-v1-5', '--pretrained_model_ckpt=models\\Stable-diffusion\\lofi_v4.safetensors', '--train_data_dir=outputs\\easyphoto-scene-id-infos\\lu1201\\processed_images', '--caption_column=text', '--resolution=768', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--dataloader_num_workers=0', '--max_train_steps=800', '--checkpointing_steps=100', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--train_text_encoder', '--seed=42', '--rank=256', '--network_alpha=128', '--validation_prompt=, special_scene, scene', '--validation_steps=100', '--output_dir=outputs\\easyphoto-scene-id-infos\\lu1201\\user_weights', '--logging_dir=outputs\\easyphoto-scene-id-infos\\lu1201\\user_weights', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--template_dir=extensions\\sd-webui-EasyPhoto\\models\\training_templates', '--template_mask', '--merge_best_lora_based_face_id', '--merge_best_lora_name=lu1201', '--cache_log_file=F:\\baidupan\\sd-webui启动器\\outputs/easyphoto-tmp/train_kohya_log.txt', '--train_scene_lora_bool']' returned non-zero exit status 1.

**Comment by spelistken** [comment]
Failed to obtain Lora after training, please check the training process.

**Comment by spelistken** [comment]
My lora model training always fails as a result, 555, I need help
