### ISSUE TITLE
[Bug]: ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by xxliucong** [aigc-apps/sd-webui-EasyPhoto#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Is EasyPhoto the latest version?

- [X] I have updated EasyPhoto to the latest version and the bug still exists.

### What happened?

训练LORA时报错提示：ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 动态链接库(DLL)初始化例程失败。具体如下：

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\extensions\sd-webui-EasyPhoto\scripts\train_kohya\train_lora.py", line 42, in <module>
    from diffusers import DDPMScheduler, DPMSolverMultistepScheduler, StableDiffusionInpaintPipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\diffusers\utils\import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\diffusers\utils\import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\diffusers\utils\import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\diffusers\utils\import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_inpaint because of the following error (look up to see its traceback):
Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 动态链接库(DLL)初始化例程失败。

### Steps to reproduce the problem

1. 点击开始训练之后报错

### What should have happened?

正常完成训练

### Commit where the problem happens

webui: 
EastPhoto: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
否
```

### List of enabled extensions

![9ea002e08caeda21ff70b0003324d34](https://github.com/user-attachments/assets/2f881f57-829e-42ae-83e5-a3ddf9e3469e)

### Console logs

```Shell
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\extensions\sd-webui-EasyPhoto\scripts\train_kohya\train_lora.py", line 42, in <module>
    from diffusers import DDPMScheduler, DPMSolverMultistepScheduler, StableDiffusionInpaintPipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\diffusers\utils\import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\diffusers\utils\import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\diffusers\utils\import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\diffusers\utils\import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_inpaint because of the following error (look up to see its traceback):
Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.8\sd-webui-aki-v4.8\sd-webui-aki-v4.8\python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 70, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 动态链接库(DLL)初始化例程失败。
```

**Comment by l378500947** [comment]
我也遇到了，不知道如何解决

**Comment by l378500947** [comment]
我在主板BIOS设置里打开了AVX2指令集，这个报错消失了，你可以尝试一下。
I opened the AVX2 Instruction Set Architecture in the main board BIOS settings, and this error disappeared. You can try it.

**Comment by AIxinbo** [comment]
我的AVX2指令集市打开的,但是还是报错,有没有其他办法

**Comment by AIxinbo** [comment]
解决办法:
1、删除SD.4.8\python\Lib\site-packages下的所有TensorFlow相关文件
2、#修改SD.4.8\extensions\sd-webui-EasyPhoto下面的install.py
#找到if not is_installed("tensorflow-cpu"),修改成
if not is_installed("tensorflow") and not is_installed("tensorflow-cpu")
3、重新安装
python\python.exe -m pip install --force-reinstall tensorflow==2.13.0
