### ISSUE TITLE
Inference failed.

### ISSUE THREAD

**Issue by njovy** [aigc-apps/sd-webui-EasyPhoto#53]
```
2023-09-10 04:31:59.415814: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
2023-09-10 04:32:02,769 - modelscope - INFO - model inference done
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 412, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint_with_mask_face(input_image, input_mask, replaced_input_image, diffusion_steps=first_diffusion_steps, denoising_strength=first_denoising_strength, input_prompt=input_prompts[index], hr_scale=1.0, seed=str(seed), sd_model_checkpoint=sd_model_checkpoint)
  File "C:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 109, in inpaint_with_mask_face
    image = i2i_inpaint_call(
  File "C:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 250, in i2i_inpaint_call
    sd_vae              = os.path.basename(find_vae_near_checkpoint(sd_vae))
  File "C:\Program Files\Python310\lib\ntpath.py", line 242, in basename
    return split(p)[1]
  File "C:\Program Files\Python310\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Above is a log that I got when I tried to generate an image with a predefined template.
Could you tell me how to fix this issue? Thank you for this extension.

**Comment by njovy** [comment]
Restart a webui fixed a problem.
