### ISSUE TITLE
[controlnet版本问题] AttributeError: 'ControlNetUnit' object has no attribute 'guess_mode'

### ISSUE THREAD

**Issue by CristianoTian** [aigc-apps/sd-webui-EasyPhoto#61]
*** Error running process: /tmp-data/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/tmp-data/workspace/stable-diffusion-webui/modules/scripts.py", line 519, in process
        script.process(p, *script_args)
      File "/tmp-data/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1046, in process
        self.enabled_units = self.get_enabled_units(p)
      File "/tmp-data/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1009, in get_enabled_units
        unit = self.parse_remote_call(p, unit, idx)
      File "/tmp-data/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 874, in parse_remote_call
        unit.guess_mode = selector(p, "control_net_guess_mode", unit.guess_mode, idx)
    AttributeError: 'ControlNetUnit' object has no attribute 'guess_mode'

---

虽然报错，但是可以生成图片， 不知道会不会对生成的图片质量有影响。

**Comment by wuziheng** [comment]
理论上可能是controlnet插件版本问题，如果对当前的ID效果影响不大，可以忽略先。我们会记录下这个问题，也帮忙提供一下controlnet版本。

**Comment by CristianoTian** [comment]
> 理论上可能是controlnet插件版本问题，如果对当前的ID效果影响不大，可以忽略先。我们会记录下这个问题，也帮忙提供一下controlnet版本。

v1.1.132

**Comment by wuziheng** [comment]
谢谢，我们求证一下之后再看看如何解决，并关闭这一issue

**Comment by wuziheng** [comment]
已验证无后续影响。
