### ISSUE TITLE
秋叶整合包，SD1.6 安装报错

### ISSUE THREAD

**Issue by majnn** [aigc-apps/sd-webui-EasyPhoto#74]
*** Error running install.py for extension D:\01_AI\sd-webui-aki\extensions\sd-webui-EasyPhoto.
*** Command: "D:\01_AI\sd-webui-aki\python\python.exe" "D:\01_AI\sd-webui-aki\extensions\sd-webui-EasyPhoto\install.py"
*** Error code: 1
*** stdout: Installing requirements for easyphoto-webui
*** Installing requirements for tensorflow
*** Installing requirements for easyphoto-webui
*** Installing requirements for ifnude
*** 
*** stderr: Traceback (most recent call last):
***   File "D:\01_AI\sd-webui-aki\extensions\sd-webui-EasyPhoto\install.py", line 22, in <module>
***     launch.run_pip("install ifnude", "requirements for ifnude")
***   File "D:\01_AI\sd-webui-aki\.launcher\pyinterop.hfkx1kkk0g4q7.zip\swlpatches\progress\launch.py", line 49, in wrapped_run_pip
***   File "D:\01_AI\sd-webui-aki\modules\launch_utils.py", line 138, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "D:\01_AI\sd-webui-aki\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install requirements for ifnude.
*** Command: "D:\01_AI\sd-webui-aki\python\python.exe" -m pip install ifnude --prefer-binary
*** Error code: 1
*** stdout: Collecting ifnude
***   Using cached ifnude-0.0.3-py2.py3-none-any.whl (7.1 kB)
*** Requirement already satisfied: pillow in d:\01_ai\sd-webui-aki\python\lib\site-packages (from ifnude) (9.5.0)
*** Collecting opencv-python-headless>=4.5.1.48 (from ifnude)
***   Using cached opencv_python_headless-4.8.0.76-cp37-abi3-win_amd64.whl (38.0 MB)
*** Requirement already satisfied: tqdm in d:\01_ai\sd-webui-aki\python\lib\site-packages (from ifnude) (4.65.0)
*** Requirement already satisfied: scikit-image in d:\01_ai\sd-webui-aki\python\lib\site-packages (from ifnude) (0.21.0)
*** Collecting onnxruntime (from ifnude)
***   Using cached onnxruntime-1.15.1-cp310-cp310-win_amd64.whl (6.7 MB)
*** Requirement already satisfied: numpy>=1.21.2 in d:\01_ai\sd-webui-aki\python\lib\site-packages (from opencv-python-headless>=4.5.1.48->ifnude) (1.23.5)
*** Requirement already satisfied: coloredlogs in d:\01_ai\sd-webui-aki\python\lib\site-packages (from onnxruntime->ifnude) (15.0.1)
*** Requirement already satisfied: flatbuffers in d:\01_ai\sd-webui-aki\python\lib\site-packages (from onnxruntime->ifnude) (23.3.3)
*** Requirement already satisfied: packaging in d:\01_ai\sd-webui-aki\python\lib\site-packages (from onnxruntime->ifnude) (23.1)
*** Requirement already satisfied: protobuf in d:\01_ai\sd-webui-aki\python\lib\site-packages (from onnxruntime->ifnude) (3.20.3)
*** Requirement already satisfied: sympy in d:\01_ai\sd-webui-aki\python\lib\site-packages (from onnxruntime->ifnude) (1.11.1)
*** Requirement already satisfied: scipy>=1.8 in d:\01_ai\sd-webui-aki\python\lib\site-packages (from scikit-image->ifnude) (1.10.1)
*** Requirement already satisfied: networkx>=2.8 in d:\01_ai\sd-webui-aki\python\lib\site-packages (from scikit-image->ifnude) (3.1)
*** Requirement already satisfied: imageio>=2.27 in d:\01_ai\sd-webui-aki\python\lib\site-packages (from scikit-image->ifnude) (2.28.1)
*** Requirement already satisfied: tifffile>=2022.8.12 in d:\01_ai\sd-webui-aki\python\lib\site-packages (from scikit-image->ifnude) (2023.4.12)
*** Requirement already satisfied: PyWavelets>=1.1.1 in d:\01_ai\sd-webui-aki\python\lib\site-packages (from scikit-image->ifnude) (1.4.1)
*** Requirement already satisfied: lazy_loader>=0.2 in d:\01_ai\sd-webui-aki\python\lib\site-packages (from scikit-image->ifnude) (0.2)
*** Requirement already satisfied: colorama in d:\01_ai\sd-webui-aki\python\lib\site-packages (from tqdm->ifnude) (0.4.6)
*** Requirement already satisfied: humanfriendly>=9.1 in d:\01_ai\sd-webui-aki\python\lib\site-packages (from coloredlogs->onnxruntime->ifnude) (10.0)
*** Requirement already satisfied: mpmath>=0.19 in d:\01_ai\sd-webui-aki\python\lib\site-packages (from sympy->onnxruntime->ifnude) (1.3.0)
*** Requirement already satisfied: pyreadline3 in d:\01_ai\sd-webui-aki\python\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime->ifnude) (3.4.1)
*** Installing collected packages: opencv-python-headless, onnxruntime, ifnude
*** 
*** stderr: WARNING: Ignoring invalid distribution -rotobuf (d:\01_ai\sd-webui-aki\python\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (d:\01_ai\sd-webui-aki\python\lib\site-packages)
*** ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'D:\\01_AI\\sd-webui-aki\\python\\Lib\\site-packages\\cv2\\cv2.pyd'
*** Consider using the `--user` option or check the permissions.

**Comment by majnn** [comment]
直接下载压缩文件，然后放到extension目录下，再打开，自动安装成功
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/55217559/b5e4ca97-ebe1-4c4a-9c3f-df9b0472f412)
