### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by tankzhangying** [aigc-apps/sd-webui-EasyPhoto#81]
Traceback (most recent call last):
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/home/t8/.conda/envs/py310/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/home/t8/.conda/envs/py310/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/t8/.conda/envs/py310/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/t8/.conda/envs/py310/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/home/t8/.conda/envs/py310/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/home/t8/.conda/envs/py310/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/t8/.conda/envs/py310/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/t8/.conda/envs/py310/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/modelscope/hub/file_download.py", line 290, in http_get_file
    r = requests.get(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/ai/t8/webui-easyphoto/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 215, in easyphoto_infer_forward
    image_face_fusion       = pipeline(Tasks.image_face_fusion, model='damo/cv_unet-image-face-fusion_damo')
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 106, in pipeline
    model = normalize_model_input(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 33, in normalize_model_input
    model = snapshot_download(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/modelscope/hub/snapshot_download.py", line 149, in snapshot_download
    http_get_file(
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/modelscope/hub/file_download.py", line 316, in http_get_file
    retry = retry.increment('GET', url, error=e)
  File "/ai/t8/webui-easyphoto/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: None: Max retries exceeded with url: http://www.modelscope.cn/api/v1/models/damo/cv_unet-image-face-fusion_damo/repo?Revision=v1.2&FilePath=description/.DS_Store (Caused by ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))))

**Comment by wuziheng** [comment]
似乎是由于网络问题无法加载modelscope 模型，请多重试几次。如果还不行，可以等待我们更新全包环境的docker更新。

**Comment by Antonyrahul** [comment]
Hi i am getting this error . I can assure that there is no network issue
