### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by h3clikejava** [aigc-apps/sd-webui-EasyPhoto#83]
Traceback (most recent call last):
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/h3c/Documents/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 251, in easyphoto_infer_forward
    template_images = eval(selected_template_images)
  File "<string>", line 0
    
SyntaxError: invalid syntax

**Comment by h3clikejava** [comment]
*** Error running process: /home/h3c/Documents/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/home/h3c/Documents/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/home/h3c/Documents/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "/home/h3c/Documents/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/home/h3c/Documents/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "/home/h3c/Documents/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "/home/h3c/Documents/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 351, in build_control_model
        network.to('cpu', dtype=p.sd_model.dtype)
    AttributeError: 'NoneType' object has no attribute 'dtype'

---
Traceback (most recent call last):
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/h3c/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/h3c/Documents/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 434, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint_with_mask_face(input_image, input_mask, replaced_input_image, diffusion_steps=first_diffusion_steps, denoising_strength=first_denoising_strength, input_prompt=input_prompts[index], hr_scale=1.0, seed=str(seed), sd_model_checkpoint=sd_model_checkpoint)
  File "/home/h3c/Documents/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/easyphoto_infer.py", line 110, in inpaint_with_mask_face
    image = i2i_inpaint_call(
  File "/home/h3c/Documents/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/sdwebui.py", line 302, in i2i_inpaint_call
    processed = processing.process_images(p_img2img)
  File "/home/h3c/Documents/stable-diffusion-webui/modules/processing.py", line 732, in process_images
    res = process_images_inner(p)
  File "/home/h3c/Documents/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/home/h3c/Documents/stable-diffusion-webui/modules/processing.py", line 801, in process_images_inner
    with torch.no_grad(), p.sd_model.ema_scope():
AttributeError: 'NoneType' object has no attribute 'ema_scope'
Creating model from config: /home/h3c/Documents/stable-diffusion-webui/configs/v1-inference.yaml
Loading VAE weights specified in settings: /home/h3c/Documents/stable-diffusion-webui/models/VAE/vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.

**Comment by bubbliiiing** [comment]
Could you please confirm if controlnet is functioning properly and provide the version? The error is being reported in controlnet, which is not a common error.

**Comment by wuziheng** [comment]
@h3clikejava  是否可以更新版本再次尝试，当前版本已经引入了对所有模型第一次推理前的hash check，如果都没问题，应该不会在出现您提到的问题。
@h3clikejava, can you update the version and try again? The current version has introduced a hash check for all models before the first inference, so if there are no issues with that, you shouldn't encounter the problem you mentioned.
