### ISSUE TITLE
训练报错  链接超时 

### ISSUE THREAD

**Issue by guanshiang** [aigc-apps/sd-webui-EasyPhoto#84]
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com', port=443): Max retries exceeded with url: /webui/ChilloutMix-ni-fp16.safetensors (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001F03D4A40A0>, 'Connection to pai-aigc-photog.oss-cn-hangzhou.aliyuncs.com timed out. (connect timeout=None)'))

**Comment by guanshiang** [comment]
训练可以了， 生图又报错了 
Traceback (most recent call last):
  File "E:\AI\sd-webui-aki-v4.1\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\AI\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\sd-webui-aki-v4.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\sd-webui-aki-v4.1\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 387, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(input_image, input_mask, controlnet_pairs, diffusion_steps=first_diffusion_steps, denoising_strength=first_denoising_strength, input_prompt=input_prompts[index], hr_scale=1.0, seed=str(seed), sd_model_checkpoint=sd_model_checkpoint)
  File "E:\AI\sd-webui-aki-v4.1\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 121, in inpaint
    image = i2i_inpaint_call(
  File "E:\AI\sd-webui-aki-v4.1\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 249, in i2i_inpaint_call
    sd_model_checkpoint = get_closet_checkpoint_match(sd_model_checkpoint).model_name
AttributeError: 'NoneType' object has no attribute 'model_name'

**Comment by yunkchen** [comment]
models 目录下能找到 ChilloutMix-ni-fp16.safetensors 模型么？看起来是没有下载成功

**Comment by guanshiang** [comment]
感谢，可以了， 改了一行代码可以了。
    #sd_model_checkpoint = get_closet_checkpoint_match(sd_model_checkpoint).model_name
    sd_model_checkpoint = "Chilloutmix-Ni-pruned-fp16-fix.safetensors"
