### ISSUE TITLE
更新后预处理异常

### ISSUE THREAD

**Issue by Wallfacer005CN** [aigc-apps/sd-webui-EasyPhoto#89]
今天更新后，预处理阶段总是报错：
0it [00:00, ?it/s]2023-09-15 13:01:22,030 - modelscope - WARNING - task skin-retouching-torch input definition is missing
2023-09-15 13:01:22,113 - modelscope - WARNING - task skin-retouching-torch output keys are missing
0it [00:00, ?it/s]
Exception in thread Thread-8 (preprocess_images):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/workspace/demos/stable_diffusion_easyphoto/stable-diffusion-webui/extensions/sd-webui-EasyPhoto/scripts/preprocess.py", line 157, in preprocess_images
    sub_box     = sub_boxes[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by bubbliiiing** [comment]
![image](https://github.com/aigc-apps/sd-webui-EasyPhoto/assets/47347516/3735adf5-c911-4fc0-bc95-b586fadc979f)
是不是搞错了157行不是你的那句

**Comment by Wallfacer005CN** [comment]
> ![image](https://user-images.githubusercontent.com/47347516/268331955-3735adf5-c911-4fc0-bc95-b586fadc979f.png) 是不是搞错了157行不是你的那句

应该是上一句sub_b0x[0]那里取不到值，看报错的意思，可能sub_box为空数组。

**Comment by bubbliiiing** [comment]
> > ![image](https://user-images.githubusercontent.com/47347516/268331955-3735adf5-c911-4fc0-bc95-b586fadc979f.png) 是不是搞错了157行不是你的那句
> 
> 应该是上一句sub_b0x[0]那里取不到值，看报错的意思，可能sub_box为空数组。

yes 不过这个问题特别少见，我们会后面加一个try来防止这个错误的发生。

**Comment by wuziheng** [comment]
请更新到最新版本，当前
https://github.com/aigc-apps/sd-webui-EasyPhoto/blob/0d24d8cddcf32d706f70580cb471068c1792e5a6/scripts/preprocess.py#L219
已添加容错并修复相关问题。谢谢关注。
