### ISSUE TITLE
UnboundLocalError: local variable 'face_analyser' referenced before assignment

### ISSUE THREAD

**Issue by ultimatech-cn** [aigc-apps/sd-webui-EasyPhoto#92]
Just install the easyphoto, got errors when training as following
```
2023-09-16 20:22:44,106 - httpx - HTTP Request: POST http://localhost:7861/api/predict "HTTP/1.1 200 OK"
1it [00:01,  1.04s/it]
save processed image to D:\stable-diffusion-webui\outputs/easyphoto-user-id-infos\maomao001\processed_images\train\0.jpg
Exception in thread Thread-71 (preprocess_images):
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\miniconda3\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\preprocess.py", line 205, in preprocess_images
    del face_analyser
UnboundLocalError: local variable 'face_analyser' referenced before assignment
```

**Comment by bubbliiiing** [comment]
Fixed, 3Q
