### ISSUE TITLE
When generating photoes, error reported. AttributeError: 'NoneType' object has no attribute 'model_name'

### ISSUE THREAD

**Issue by ultimatech-cn** [aigc-apps/sd-webui-EasyPhoto#93]
2023-09-16 20:26:52,619 - modelscope - INFO - model inference done
2023-09-16 20:26:52,626 - root - Start First diffusion.
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 379, in easyphoto_infer_forward
    first_diffusion_output_image = inpaint(input_image, input_mask, controlnet_pairs, diffusion_steps=first_diffusion_steps, denoising_strength=first_denoising_strength, input_prompt=input_prompts[index], hr_scale=1.0, seed=str(seed), sd_model_checkpoint=sd_model_checkpoint)
  File "D:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\easyphoto_infer.py", line 120, in inpaint
    image = i2i_inpaint_call(
  File "D:\stable-diffusion-webui\extensions\sd-webui-EasyPhoto\scripts\sdwebui.py", line 249, in i2i_inpaint_call
    sd_model_checkpoint = get_closet_checkpoint_match(sd_model_checkpoint).model_name
AttributeError: 'NoneType' object has no attribute 'model_name'

**Comment by bubbliiiing** [comment]
Fixed, 3Q

**Comment by ultimatech-cn** [comment]
It is ok.  Is that because the model file has not downloaded?
