### ISSUE TITLE
生图的时候报错 ControlNet v1.1.410

### ISSUE THREAD

**Issue by waaaok** [aigc-apps/sd-webui-EasyPhoto#97]
2023-09-19 02:48:57,954 - ControlNet - INFO - Loading model: control_v11f1e_sd15_tile [a371b31b]
*** Error running process: F:\aipic\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "F:\aipic\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "F:\aipic\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "F:\aipic\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "F:\aipic\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "F:\aipic\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "F:\aipic\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 349, in build_control_model
        state_dict = load_state_dict(model_path)
      File "F:\aipic\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 20, in load_state_dict
        state_dict = unsafe_torch_load(ckpt_path, map_location=torch.device(location))
      File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 797, in load
        with _open_zipfile_reader(opened_file) as opened_zipfile:
      File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 283, in __init__
        super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
    RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by yunkchen** [comment]
try this:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1513#issuecomment-1265362817

**Comment by waaaok** [comment]
restore face?

**Comment by waaaok** [comment]
restore face？
我似乎在除了使用easyphoto外，在用webui时遇到过这种问题，平时都可以正常使用controlnet和restore face

**Comment by bubbliiiing** [comment]
这个问题来源于权重未下载完整，估计下载的时候网络有点问题。

**Comment by wuziheng** [comment]
@waaaok 请尝试新版本并关注log信息，当前版本已经有模型hash检测，如果不完全会报错，请注意修复。
